#!/bin/sh

ln -s libc-1.0.so libc.so
ln -s libdeft-0.1.so libdeft.so
ln -s libdrawengine-0.1.so libdrawengine.so
ln -s libft-2.4.6-1.so libft.so
ln -s libgcc-4.6.1.so libgcc.so
ln -s libjpeg-62.so libjpeg.so
ln -s liblua-5.1.4.so liblua.so
#ln -s libluajit2.0.0-1.so libluajit.so
ln -s libluajit2.0.0-2.so libluajit.so
ln -s libm-1.0.so libm.so
ln -s libpng-12.so libpng.so
ln -s libsigc-2.0.so libsigc.so
ln -s libstdc++-1.2.2.so libstdc++.so
ln -s libunzip-1.01.so libunzip.so
ln -s libxvidcore-4.3.so libxvidcore.so
ln -s libz-1.2.5.so libz.so
ln -s libzzip-0.36.so libzzip.so
