#ifndef _LNG_H
#define _LNG_H

#define psz_savestate	"Save last panels state"
#define psz_backexit	"Back in root - Exit"
#define psz_sconchk		"Move cursor down on check"
#define psz_loopnav		"Enable loop navigation"

#define psz_scspeed		"Text scroll speed"
#define psz_scwait		"Text scroll wait"
#define psz_useboldf	"Use bold font"

#define psz_loadicons	"Load mcfileico.cfg"
#define psz_loadkeys	"Load mckeys.cfg"
#define psz_loadmui		"Load default.mclg"
#define psz_loadcs		"Load default.mccs"
#define psz_configpath	"mcconfig.cfg path"

#define psz_showhiddrv	"Show hidden drives"
#define psz_showmmc		"Show MMC"
#define psz_showhidden	"Show hidden files"
#define psz_showsystem	"Show system files"

#define psz_confirmexit	"On exit"
#define psz_confirmdel	"On delete"
#define psz_confirmdelr	"On delete readonly"
#define psz_confirmcopy	"On copy"
#define psz_confirmmove	"On move"
#define psz_confirmrepl	"On replace"

#define psz_autoexit_after			"AutoExit after (min)"
#define psz_autoexit_on_background	"AutoExit on background"

#define psz_zip_enable		"Enable zip support"
#define psz_zip_detect_by	"Detect zip by"
#define psz_temppath		"Path for temp files"
#define psz_cleartemp		"Delete temp files on exit"

#define psz_about		"mc v"version" \n(c) 2007 weclnt, greengo7\nThanks for efficient advices: Aru55, 1nvisible, captain_SISka"

#define psz_no			"No"
#define psz_yes			"Yes"

#define psz_content		"Content"
#define psz_extension	"Extension"

#define psz_drv_0		"Data"
#define psz_drv_1		"Cache"
#define psz_drv_2		"Config"
#define psz_drv_4		"MMC"

#define psz_mcvol		"MC"
#define psz_zipvol		"ZIP"

#define psz_errfile		"?"

#define psz_sm_common	"Common"
#define psz_sm_confirms	"Confirmations"
#define psz_sm_configs	"Configs"
#define psz_sm_disks	"Disks and files"
#define psz_sm_gui		"GUI"
#define psz_sm_autoexit	"AutoExit"
#define psz_sm_zip		"Zip"


#define sz_no			"Нет"
#define sz_yes			"Да"

#define sz_byte			"б"
#define sz_kbyte		"Кб"
#define sz_mbyte		"Мб"

#define sz_reconfig		"Конфигу-\nрация обновлена!"
#define sz_lng			"Язык"
#define sz_lngname		"Русский"

#define sz_dirmking		"Создание папок"
#define sz_copying		"Копирование"
#define sz_moveing		"Перемещение"
#define sz_deling		"Удаление"

#define sz_mcmenu		"Меню MC"
#define sz_select		"Выбор"
#define sz_back			"Назад"

#define sz_open			"Открыть"
#define sz_file_m		"Файл..."
#define sz_chk				"Выделить"
#define sz_chkall			"Выделить все"
#define sz_invchk			"Инвертировать"
#define sz_unchall			"Сбросить все"
#define sz_oper_m		"Операции..."
#define sz_past				"Вставить"
#define sz_cancel			"Отменить"
#define sz_copy				"Копировать"
#define sz_move				"Переместить"
#define sz_del				"Удалить"
#define sz_rename			"Переименовать"
#define sz_newdir			"Новая папка"
#define sz_newfile			"Новый файл"
#define sz_prop			"Свойства"
#define sz_view_m		"Вид..."
#define sz_sort_m			"Сортировка..."
#define sz_sortn				"По имени"
#define sz_sorte				"По типу"
#define sz_sorts				"По размеру"
#define sz_sortd				"По дате"
#define sz_sortr				"Обратная"
#define sz_filter			"Фильтр"
#define sz_refresh			"Обновить"
#define sz_misc_m		"Разное..."
#define sz_bm_m				"Закладки..."
#define sz_add					"Добавить"
#define sz_bml					"Список"
#define sz_drvinf			"Диски"
#define sz_settings			"Настройки"
#define sz_about_m			"Об эльфе..."
#define sz_exit			"Выход"

#define sz_bm			"Закладка"

#define sz_name			"Имя"
#define sz_fullname		"Полное имя"
#define sz_size			"Размер"
#define sz_global		"Общий"
#define sz_folders		"Папок"
#define sz_files		"Файлов"
#define sz_date			"Дата создания"
#define sz_attr			"Атрибуты"
#define sz_readonly		"Только чтение"
#define sz_hidden		"Скрытый"
#define sz_system		"Системный"
#define sz_arh			"Архивный"
#define sz_subdirs		"Обрабатывать подкаталоги"
#define sz_ncsize		"Несжатый"
#define sz_csize		"Сжатый"
#define sz_cglobal		"Общий сжатый"

#define sz_pmt_del		"Удалить?"
#define sz_pmt_rodel	"Файл %s только для чтения.\nУдалить?"
#define sz_pmt_copy		"Копировать?"
#define sz_pmt_move		"Переме-\nстить?"
#define sz_pmt_stop		"Прервать?"
#define sz_pmt_cancel	"Очистить буфер?"
#define sz_pmt_exists	"Файл существует. Заменить?"
#define sz_pmt_exit		"Выйти из MC?"
#define sz_pmt_impcs	"Применить цветовую схему?"
#define sz_pmt_implg	"Применить язык?"

#define sz_err_attrset		"Не удалось задать атрибуты!"
#define sz_err_makedir		"Не удалось создать папку!"
#define sz_err_rename		"Не удалось переиме-\nновать!"
#define sz_err_delete		"Не удалось удалить!"
#define sz_err_badname_t	"Неверное имя: %t"
#define sz_err_baddrv_t		"Неверный диск! %t"
#define sz_err_resnok		"Выполнено с ошибками!"
#define sz_err_nofiles		"Нет файлов!"
#define sz_err_badname		"Неверное имя!"
#define sz_err_badkey		"Ошибка конфигурации кнопок!"
#define sz_err_badformat	"Неверный формат или файл поврежден!"
#define sz_err_nomemory		"Не хватает памяти!"
#define sz_err_makefile		"Не удалось создать новый файл!"
#define sz_err_ziperr		"Ошибка Zip: %d в %t!"

#define sz_msg_zreading			"Чтение архива"
#define sz_msg_showhid_files	"Показывать скрытые файлы"
#define sz_msg_showsys_files	"Показывать системные файлы"
#define sz_msg_showhidsys_files	"Показывать скрытые и системные файлы"
#define sz_msg_showhid_drv		"Показывать скрытые диски"

#endif
