#ifndef _LANG_H_
#define _LANG_H_

#define ELFNAME		"Master.elf"
#define COPYRIGHT	"Master.elf\n(c) BingK(binghelingxi)\n(r) all the author of CfgEdit!"

#define LANG_CN
//#define LANG_EN

#ifdef LANG_CN

#define ERR_STR			"错误!"
#define LGP_EXIT		"离开"
#define LGP_SELECT		"选择"
#define LGP_MENU		"菜单"
#define LGP_OPTIONS		"选项"
#define LGP_ONOFF		"开/关"
#define LGP_QUIT		"退出"
#define LGP_ABOUT		"关于..."
#define LGP_NOTSUPPORT	"不支持的条目"
#define LGP_ENTER		"进入"
#define LGP_CBOX_ERR	"错误的选项"
#define LGP_OK			"完成"
#define	LGP_BACK		"返回"
#define LGP_CLOSE		"关闭"
#define LGP_SELECT_FILE	"选择文件"
#define LGP_SELECT_FOLDER	"选择文件夹"
#define LGP_PROFILE		"情景模式"
/*#define LGP_PROFILE1	"情景模式1"
#define LGP_PROFILE2	"情景模式2"
#define LGP_PROFILE3	"情景模式3"
#define LGP_PROFILE4	"情景模式4"
#define LGP_PROFILE5	"情景模式5"
#define LGP_PROFILE6	"情景模式6"
#define LGP_PROFILE7	"情景模式7"*/
#define LGP_DEL_ALL		"清除所有配置"
#define LGP_RELOAD_CONFIG_ERR	"重新读取配置失败!"
#define LGP_DEL_THIS	"清除该补丁配置"
#define LGP_DEL_UNUSED	"清除无用配置"
#define LGP_PATCH_NAME	"补丁:"
#define LGP_PATCH_AUTHOR	"作者:"
#define LGP_PATCH_ID	"ID:"
#define LGP_PATCH_VERSION	"版本:"
#define LGP_PATCH_INFO_OTH	"其它信息:"
#define LGP_PATCH_INFO	"补丁信息"
#define LGP_BACKUP		"备份配置"
#define LGP_RESTORE		"恢复备份"
#define LGP_BACKUP_PATH "备份文件路径:"
#define LGP_RESTORE_PATH	"恢复备份路径:"
#define LGP_ENTER_PATH	"输入文件夹路径"
#define LGP_IS_OFF		"已关闭"
#define	LGP_QUIT_WITHOUT_RS	"不刷新MP退出"
#endif

#ifdef LANG_EN
#define ERR_STR			"Error!"
#define LGP_EXIT		"Exit"
#define LGP_SELECT		"Select"
#define LGP_MENU		"Menu"
#define LGP_OPTIONS		"Options"
#define LGP_ONOFF		"On/Off"
#define LGP_QUIT		"Quit"
#define LGP_ABOUT		"About..."
#define LGP_NOTSUPPORT	"ItemNotSupported"
#define LGP_ENTER		"Enter"
#define LGP_CBOX_ERR	"ChoiceIndexError!"
#define LGP_OK			"OK"
#define	LGP_BACK		"Back"
#define LGP_CLOSE		"Close"
#define LGP_SELECT_FILE	"Select File"
#define LGP_SELECT_FOLDER	"Select Folder"
#define LGP_PROFILE		"Profile"
/*#define LGP_PROFILE1	"Profile1"
#define LGP_PROFILE2	"Profile2"
#define LGP_PROFILE3	"Profile3"
#define LGP_PROFILE4	"Profile4"
#define LGP_PROFILE5	"Profile5"
#define LGP_PROFILE6	"Profile6"
#define LGP_PROFILE7	"Profile7"*/
#define LGP_DEL_ALL		"Clear All Configs"
#define LGP_RELOAD_CONFIG_ERR	"Reload Config Error!"
#define LGP_DEL_THIS	"Clear This Config"
#define LGP_DEL_UNUSED	"Clear Unused Configs"
#define LGP_PATCH_NAME	"Name:"
#define LGP_PATCH_AUTHOR	"Author:"
#define LGP_PATCH_ID	"ID:"
#define LGP_PATCH_VERSION	"Version:"
#define LGP_PATCH_INFO_OTH	"Other Info:"
#define LGP_PATCH_INFO	"Info"
#define LGP_BACKUP		"Backup Configs"
#define LGP_RESTORE		"Restore Configs"
#define LGP_BACKUP_PATH "Backup Path:"
#define LGP_RESTORE_PATH	"Restore Path:"
#define LGP_ENTER_PATH	"Enter Folder Path"
#define LGP_IS_OFF		"Is Off"
#define	LGP_QUIT_WITHOUT_RS	"Quit Without RunScaner"
#endif
#endif
