

#define ELF_NAME "MediaPlayerPlus"
#define COPYRIGHT "MediaPlayerPlus\n(c) 2008\nBingK,binghelingxi"

#define LANG_CN

#ifdef LANG_CN
#define CS_NAMEDRW "歌曲名显示"
#define CS_POS "坐标位置"
#define CS_LENGTH "显示宽度"
#define CS_SHOWLOCK "锁键盘时显示"
#define CS_FONT "歌曲名字体"
#define CS_COLOR "歌曲名颜色"
#define CS_FRMCOLOR "歌曲名背景颜色"
#define CS_ATTR "文本属性"
#define CS_FRMLEV "外框设定"
#define CS_FRAMMAINCOLOR "边框颜色"
#define CS_FRMBGCOLOR "背景颜色"
#define CS_XRND "X弯曲"
#define CS_YRND "Y弯曲"
#define CS_FRMSTYLE "样式" 
#define CS_BROKEN_LINE "虚线"
#define CS_SOLID_LINE "实线"
#define CS_SPEED "滚动速度(毫秒)"
#define CS_WAIT "滚动延迟(毫秒)"
#define CS_CSMADDR "媒体播放器CSM"

//#define CS_EXTCTRL "后缀显示控制"
//#define CS_SHOW_ALL "所有文件类型"
//#define CS_SHOW_ADVD "显示视频音频文件"
#define CS_SHOW_GP "显示图形文件"
//#define CS_SHOW_NO "不显示所有后缀"
#define CS_SHOW_EXT "显示后缀"

//#define CS_KEYCTRL "按键控制"
//#define CS_KEY_ENA "允许按键控制"
//#define CS_KEYPP "播放/暂停"
//#define CS_KEYPRE "上一首"
//#define CS_KEYNEXT "下一首"
//#define CS_KEY_0 "数字键0"
//#define CS_KEY_1 "数字键1"
//#define CS_KEY_2 "数字键2"
//#define CS_KEY_3 "数字键3"
//#define CS_KEY_4 "数字键4"
//#define CS_KEY_5 "数字键5"
//#define CS_KEY_6 "数字键6"
//#define CS_KEY_7 "数字键7"
//#define CS_KEY_8 "数字键8"
//#define CS_KEY_9 "数字键9"
//#define CS_KEY_X "*键"
//#define CS_KEY_J "#键"
//#define CS_KEY_LS "左软键"
//#define CS_KEY_RS "右软键"
//#define CS_KEY_GB "绿键"
//#define CS_KEY_RB "红键"
//#define CS_KEY_LB "方向键左"
//#define CS_KEY_RB1 "方向键右"
//#define CS_KEY_UB "方向键上"
//#define CS_KEY_DB "方向键下"
//#define CS_KEY_EB "中键"
//#define CS_KEY_IB "上网键"
#define CS_LRCCTRL "歌词显示控制"
#define CS_LRC_ENA "允许显示歌词"
#define CS_LRC_DIR_PATH "歌词文件夹路径"
#define CS_LRC_FONT "歌词字体"
#define CS_LRC_COLOR "歌词颜色"
#define CS_LRC_FRMCOLOR "边框颜色"
#define CS_LRC_SPEED "歌词滚动速度"
#define CS_LRC_ATTR "歌词文本属性"


#define LGP_UPDATE_CONFIG "MediaPlayerPlus配置更新!"

#endif


#ifdef LANG_EN

#define CS_NAMEDRW "SongName Ctrl"
#define CS_POS "Postion"
#define CS_LENGTH "Width"
#define CS_SHOWLOCK "Show Lock"
#define CS_FONT "Font"
#define CS_COLOR "Color"
#define CS_FRMCOLOR "Brush Color"
#define CS_ATTR "Text Attr"
#define CS_FRMLEV "Frame Setting"
#define CS_FRAMMAINCOLOR "Frame Color"
#define CS_FRMBGCOLOR "BG Color"
#define CS_XRND "X Round"
#define CS_YRND "Y Round"
#define CS_FRMSTYLE "Style" 
#define CS_BROKEN_LINE "Broken"
#define CS_SOLID_LINE "Solid"
#define CS_SPEED "Scroll Speed"
#define CS_WAIT "Wait for Scroll"
#define CS_CSMADDR "Player CSM Addr"
#define CS_SHOW_GP "Show Graphic"
#define CS_SHOW_EXT "Show Externsion"
#define CS_LRCCTRL "Lyrics Show Ctrl"
#define CS_LRC_ENA "Enable Show Lyrics"
#define CS_LRC_DIR_PATH "Lyrics Dir Path"
#define CS_LRC_FONT "Font"
#define CS_LRC_COLOR "Color"
#define CS_LRC_FRMCOLOR "Brush Color"
#define CS_LRC_SPEED "Scroll Speed"
#define CS_LRC_ATTR "Text Attr"


#define LGP_UPDATE_CONFIG "MediaPlayerPlus config updated!"

#endif
