/*
    SieNatJabber Project
 Language
*/
#include "setlang.h"
#ifndef _LANG_H_
#define _LANG_H_

#define LG_COPYRIGHT "Siemens natJabber Client\n(c)Kibab, Ad, Borman99\n%s r%i\nCompiled %s"

///////////////////////////////////////////////////////////////////////////////////////////
//
//    Russian : Недоработан!
//
///////////////////////////////////////////////////////////////////////////////////////////
#ifdef LANG_RU
#define LG_SELECT           "Выбор"
#define LG_BACK             "Назад"
#define LG_OK               "OK"
#define LG_CLOSE            "Закрыть"
#define LG_MENU             "Меню"
#define LG_CANCEL           "Отмена"
#define LG_EXIT             "Выход"
#define LG_HELP             "Помощь"
#define LG_UPDATE           "Обновить"
//status_schange.c
#define LG_STATUSSEL        "Выбор статуса"
#define LG_STONLINE         "Онлайн"
#define LG_STCHAT           "Готов болтать"
#define LG_STAWAY           "Отсутствую"
#define LG_STXA             "Недоступен"
#define LG_STDND            "Занят"
#define LG_STINVIS          "Инвиз"
#define LG_STOFFLINE        "Оффлайн"
#define LG_STATUS           "Статус"
#define LG_ENTERTEXTSTATUS  "Введите текст статуса:"
#define LG_PRIORITY         "Приоритет:"
//MUC_Enter_UI.c
#define LG_NONAMECONF       "Имя конфы не заполнено!"
#define LG_ENTERMUC         "Вход в MUC"
#define LG_NAMEMUC          "Имя конференции:"
#define LG_NICK             "Ник:"
#define LG_GETMESSAGECOUNT  "Получить сообщений:"
#define LG_ENTER            "Войти"
//message_list.c
#define LG_NOSENDNULLMESS   "Нельзя послать пустое сообщение!"
#define LG_NEW              "Новое..."
//message_cmds.c
#define LG_SELCOMMAND       "Выбор команды..."
#define LG_SELTEMPLATE      "Выбор шаблона..."
#define LG_SELSMILE         "Выбор смайла..."
#define LG_SELECT2          "Выбор..."
#define LG_CONTRESOURCES    "Ресурсы..."
#define LG_CONTRESOURCE     "Ники"
#define LG_COMMANDS         "Команды"
#define LG_MSGTEMPLATE      "Шаблоны сообщений"
#define LG_SMILE            "Смайлы"
#define LG_CLOSEDLG         "Закрыть диалог"
//mainmenu.c
#define LG_CONTACT          "Контакт"
#define LG_STATUS           "Статус"
#define LG_MUC              "Конференция"
#define LG_BOOKMARK         "Закладки"
#define LG_MVIBRA           "Режим вибры"
#define LG_MSOUND           "Режим звука"
#define LG_MOFFLINE         "Офф. контакты"
#define LG_PLAYER_STATUS    "Плеер-статус"
#define LG_SETTINGS         "Настройки"
#define LG_ABOUT            "Об эльфе..."
#define LG_COLOR            "Цвета"
#define LG_ADDCONTACT       "Добавить контакт"
#define LG_MOODS            "Настроения"
//main.c
#define LG_EXITSIEJC        "Покинуть SieJC?"
#define LG_ZLIBNOSASL       "ZLib не работает без SASL!"
#define LG_ENTERLOGPAS      "Введите логин/пароль!"
#define LG_PLATFORMM        "Платформа не соответствует!"
#define LG_ASTARTED         "Уже запущен"
//jabber_util.c
#define LG_MUCEXITDONE      "Выход из MUC выполнен!"
#define LG_VERINFO          "Version Info:\nName:%s\nVersion:%s\nOS:%s"
#define LG_TIMEINFO         "Time Info:\nUTC:%s\nTime Zone:%s\n:>%s"
#define LG_LASTACTIVMSG     "IDLE: %d d. %d hr. %d min. %d sec."
//item_info.c
#define LG_ITEMIHDR         "Контакт инфо"
#define LG_ELROSTER         "Элемент ростера"
#define LG_OFFLORCONTTR     "Оффлайн или контакт из транспорта"
#define LG_MUCPART          "Участник конференции"
#define LG_JTRANSP          "Данный контакт является транспортом Jabber"
#define LG_GROUPROSTER      "Группа ростера"
#define LG_RESOURCE         "Ресурс:"
#define LG_PRIORITY         "Приоритет:"
#define LG_REALJID          "Реальный JID:"
#define LG_STATUS2          "Статус:"
#define LG_PRIVILEGES       "Привилегии:"
#define LG_ROLE             "Роль:"
#define LG_POSIBLCLIENT     "Возможности клиента:"
#define LG_MUCSABJECT       "Тема:"
#define LG_ISUBSCRIBE       "Авторизация:"
//history.c
#define LG_ERRORWH          "Ошибка I/O #%u при записи истории!"
//cont_menu.c
#define LG_MENUCONTACT      "Меню контакта"
#define LG_UNKACTION        "Действие неизвестно или не поддерживается!"
#define LG_ABANDON          "Покинуть"
#define LG_MUC_ADMIN        "muc#admin"
#define LG_KIK              "Кик"
#define LG_BAN              "Бан"
#define LG_LVOISE           "Отнять голос"
#define LG_GVOISE           "Дать голос"
#define LG_PARTICIPANT      "Отнять членство"
#define LG_MEMBER           "Дать членство"
#define LG_MODERATOR        "Дать модератора"
#define LG_MODERATOR_REMOVE "Отнять модератора"
#define LG_ADMIN            "Дать админа"
#define LG_OWNER            "Дать владельца"
#define LG_VERCLIENT        "Версия клиента"
#define LG_INFOFDISC        "Инфо из Disco"
#define LG_ON               "Включить"
#define LG_OFF              "Отключить"
#define LG_NOSUPACTION      "Нет поддерживаемых действий"
#define LG_OHISTORY         "История"
#define LG_QUERYTIME        "Время клиента"
#define LG_QUERYVCARD       "vCard"
#define LG_QUERYLAST        "Бездействие"
#define LG_SUBSCR           "Подписка"
#define LG_EDIT             "Изменить"
#define LG_MUCCLEAR         "Очистить сообщения"
#define LG_SUBSCRIBE        "Запросить"
#define LG_SUBSCRIBED       "Разрешить"
#define LG_UNSUBSCRIBED     "Отклонить"
#define LG_UNSUBSCRIBE      "Удалить"
#define LG_REASON           "Причина"
//clist_util.c
#define LG_AUTHORREM        "Авторизация удалена!"
#define LG_AUTHORGRANTED    "Авторизация дана!"
#define LG_AUTHORCAME       "Пришел запрос на авторизацию"
#define LG_AUTHORDECLINE    "В авторизации отказано"

#define LG_MUCCROK          "Конференция создана успешно"
//bookmarks.c
#define LG_MENUBOOKMARK     "Меню закладок"
//config_data.c
#define LG_NO               "Нет"
#define LG_YES              "Да"
#define LG_DISABLED         "Отключить"
#define LG_ENABLED          "Включить"
#define LG_SETUPCONECT      "Настройка подключения"
#define LG_LOGIN            "Логин"
#define LG_PASSWORD         "Пароль"
#define LG_SERVER           "Сервер"
#define LG_HOST             "Хост"
#define LG_HOSTTYPE         "Тип хоста"
#define LG_HOSTNAME         "Имя"
#define LG_IPADRESS         "IP адрес"
#define LG_PORT             "Порт"
#define LG_AUTHTYPE         "Авторизация"
#define LG_ZLIBUSE          "Использование ZLib"
#define LG_RES              "Ресурс"
#define LG_HISTORY          "История"
#define LG_MUCHIST          "MUC история"
#define LG_MUCDEF           "MUC по умолчанию"
#define LG_MUCDEFMSGCOUNT   "Кол. загружаемых сообщений"
#define LG_MUCDEFNIK        "Ник по умолчанию"
#define LG_SHOWIDLEICON     "Показывать значек на idle"
#define LG_IDLEICON         "Положение значка"
#define LG_POPUPDIS         "Отображать POPUP"
#define LG_COMPOSEV         "События сообщений"
#define LG_DELIVREP         "Отчет о доставке, если требуется"
#define LG_USEATTENTION     "Принимать сигнал 'Attention'"
#define LG_FIRST_LETTER     "Первая буква заглавная"
#define LG_AUTO_JOIN        "Автовход в конференцию"

#define LG_SETUPSND         "Настройка звука"
#define LG_SETUPVIBRPWR     "Мощность вибры"
#define LG_SNDVOL           "Громкость"
#define LG_SNDMSGSND        "Звук отправки"
#define LG_SNDMSGMUC        "Звук приема из MUC"
#define LG_SNDMSGPM         "Звук приема из PM"
#define LG_SNDONLINE        "Звук статуса онлайн"
#define LG_SNDOFFLINE       "Звук статуса оффлайн"
#define LG_SNDCOMPOSING     "Звук composing-событий"

#define LG_SETUPPATH        "Настройка путей"
#define LG_PATHHIST         "История"
#define LG_PATHPIC          "Картинки"
#define LG_PATHAVATARS      "Аватары"
#define LG_PATHCMD          "Команды"
#define LG_PATHMESG         "Сообщения"
#define LG_PATHKNOWF        "Известные возможности"
#define LG_PATHSMILECFG     "Конфиг смайлов"
#define LG_PATHSMILEDIR     "Каталог смайлов"
#define LG_DEFAULTDISK      "Диск по умолчанию"
#define LG_COLORPATH        "Каталог цвет. схем"

#define LG_TEXTSTATUS       "Текст статусов"
#define LG_DEFSTATES        "Состояния по умолчанию"

#define LG_VIEW             "Вид"
#define LG_ROSTER_FONT      "Шрифт ростера"
#define LG_CHATS_FONT       "Шрифт списка сообщений"
#define LG_SMALL_NORMAL_FONT "Маленький"
#define LG_SMALL_BOLD_FONT  "Маленький жирный"
#define LG_MID_NORMAL_FONT  "Средний"
#define LG_MID_BOLD_FONT    "Средний жирный"
#define LG_LARGE_NORMAL_FONT "Большой"
#define LG_LARGE_BOLD_FONT  "Большой жирный"
#define LG_UNDERLINING      "Подчеркивание сообщений"
#define LG_KBD_LAYOUT       "\"Раскладка\" клавиатуры"
#define LG_KBD1             "Раскладка 1"
#define LG_KBD2             "Раскладка 2"
#define LG_SKROLL           "Скроллинг"

#define LG_AUTOSTATUS       "Автостатус"
#define LG_AS_ENABLED       "Включен"
#define LG_AS_TIME          "Время (в минутах)"
#define LG_AS_TEXT          "Текст"

#ifdef ICONBAR
#define LG_ICONBAR_SI       "Показывать иконку в IconBar"
#define LG_ICONSET_FILENAME "Имя файла с номерами иконок"
#endif
//vCard.c
#define LG_SHOW_AVATAR      "Показать аватару"

#define LG_VCARD_JABBERID   "JID"
#define LG_VCARD_FN         "Полное имя"
#define LG_VCARD_NICKNAME   "Ник"
#define LG_VCARD_N_FAMILY   "Фамилия"
#define LG_VCARD_N_GIVEN    "Имя"
#define LG_VCARD_N_MIDDLE   "Отчество"
#define LG_VCARD_N_PREFIX   "N_PREFIX"
#define LG_VCARD_N_SUFFIX   "N_SUFFIX"
#define LG_VCARD_BDAY       "День рождения"
#define LG_VCARD_GENDER     "Пол"
#define LG_VCARD_ORGNAME    "Название организации"
#define LG_VCARD_ORGUNIT    "Отделение организации"
#define LG_VCARD_TITLE      "Название должности"
#define LG_VCARD_ROLE       "Должность"

#define LG_VCARD_EMAIL          "E-Mail"
#define LG_VCARD_EMAIL_HOME     "EMAIL_HOME"
#define LG_VCARD_EMAIL_WORK     "EMAIL_WORK"
#define LG_VCARD_EMAIL_INTERNET "EMAIL_INTERNET"
#define LG_VCARD_EMAIL_PREF     "EMAIL_PREF"
#define LG_VCARD_EMAIL_X400     "EMAIL_X400"

#define LG_VCARD_TEL_HOME   "TEL_HOME"
#define LG_VCARD_TEL_WORK   "TEL_WORK"
#define LG_VCARD_TEL_VOICE  "TEL_VOICE"
#define LG_VCARD_TEL_FAX    "TEL_FAX"
#define LG_VCARD_TEL_PAGER  "TEL_PAGER"
#define LG_VCARD_TEL_MSG    "TEL_MSG"
#define LG_VCARD_TEL_CELL   "TEL_CELL"
#define LG_VCARD_TEL_VIDEO  "TEL_VIDEO"
#define LG_VCARD_TEL_BBS    "TEL_BBS"
#define LG_VCARD_TEL_MODEM  "TEL_MODEM"
#define LG_VCARD_TEL_ISDN   "TEL_ISDN"
#define LG_VCARD_TEL_PCS    "TEL_PCS"
#define LG_VCARD_TEL_PREF   "TEL_PREF"
#define LG_VCARD_TEL_NUMBER "TEL_NUMBER"

#define LG_VCARD_ADR_HOME   "ADR_HOME"
#define LG_VCARD_ADR_WORK   "ADR_WORK"
#define LG_VCARD_ADR_POSTAL "ADR_POSTAL"
#define LG_VCARD_ADR_PARCEL "ADR_PARCEL"
#define LG_VCARD_ADR_DOM    "ADR_DOM"
#define LG_VCARD_ADR_PREF   "ADR_PREF"
#define LG_VCARD_ADR_POBOX  "ADR_POBOX"
#define LG_VCARD_ADR_EXTADD "ADR_EXTADD"
#define LG_VCARD_ADR_STREET "ADR_STREET"
#define LG_VCARD_ADR_LOCALITY "ADR_LOCALITY"
#define LG_VCARD_ADR_REGION   "Регион(область)"
#define LG_VCARD_ADR_PCODE    "Почтовый код"
#define LG_VCARD_ADR_CTRY     "Страна"
#define LG_VCARD_URL        "Домашняя страница"
#define LG_VCARD_DESC       "О себе"
#define LG_VCARD_TZ         "Временной пояс"
#define LG_VCARD_AVATAR     "Аватара"
//jid_enter_ui
#define LG_JEDELCONTACT     "Удалить контакт:"
#define LG_JEASK            "Запросить подписку:"
#define LG_JEGROUP          "Группа:"
#define LG_JENOJID          "Нет JIDа!"
#define LG_JECONTACTHDR     "Контакт:"
//moods
#define LG_M_EMPTY          "Нет"
#define LG_M_AFRAID         "Боязнь"
#define LG_M_AMAZED         "Поражение"
#define LG_M_ANGRY          "Сердитый"
#define LG_M_ANNOYED        "Раздраженный"
#define LG_M_ANXIOUS        "Обеспокоен"
#define LG_M_AROUSED        "Разбужен"
#define LG_M_ASHAMED        "Стыд"
#define LG_M_BORED          "Скукота"
#define LG_M_BRAVE          "Храбрость"
#define LG_M_CALM           "Спокойный"
#define LG_M_COLD           "Замерз"
#define LG_M_CONFUSED       "Смущен"
#define LG_M_CONTENTED      "Довольный"
#define LG_M_CRANKY         "Шатаюсь"
#define LG_M_CURIOUS        "Любопытство"
#define LG_M_DEPRESSED      "Депрессия"
#define LG_M_DISAPPOINTED   "Разочарование"
#define LG_M_DISGUSTED      "Отвращение"
#define LG_M_DISTRACTED     "Растерян"
#define LG_M_EMBARRASSED    "Стеснительность"
#define LG_M_EXCITED        "Взволнован"
#define LG_M_FLIRTATIOUS    "Кокетливость"
#define LG_M_FRUSTRATED     "Разбитый"
#define LG_M_GRUMPY         "Сварливость"
#define LG_M_GUILTY         "Виноватый"
#define LG_M_HAPPY          "Счастливый"
#define LG_M_HOT            "Жарко"
#define LG_M_HUMBLED        "Унижен"
#define LG_M_HUMILIATED     "Оскорблен"
#define LG_M_HUNGRY         "Голоден"
#define LG_M_HURT           "Вредный"
#define LG_M_IMPRESSED      "Впечатлен"
#define LG_M_IN_AWE         "Страх"
#define LG_M_IN_LOVE        "Влюблен"
#define LG_M_INDIGNANT      "Возмущен"
#define LG_M_INTERESTED     "Заинтересован"
#define LG_M_INTOXICATED    "Опьянен"
#define LG_M_INVINCIBLE     "Неукротим"
#define LG_M_JEALOUS        "Ревность"
#define LG_M_LONELY         "Одиночество"
#define LG_M_MEAN           "Жадность"
#define LG_M_MOODY          "Капризный"
#define LG_M_NERVOUS        "Возбужден"
#define LG_M_NEUTRAL        "Нейтральный"
#define LG_M_OFFENDED       "Оскорблен"
#define LG_M_PLAYFUL        "Игривый"
#define LG_M_PROUD          "Гордость"
#define LG_M_RELIEVED       "Свобода"
#define LG_M_REMORSEFUL     "Раскаяние"
#define LG_M_RESTLESS       "Беспокойство"
#define LG_M_SAD            "Грусть"
#define LG_M_SARCASTIC      "Сарказм"
#define LG_M_SERIOUS        "Серьезный"
#define LG_M_SHOCKED        "Шокирован"
#define LG_M_SHY            "Застенчивость"
#define LG_M_SICK           "Болею"
#define LG_M_SLEEPY         "Сплю"
#define LG_M_STRESSED       "Стресс"
#define LG_M_SURPRISED      "Удивлен"
#define LG_M_THIRSTY        "Жажда"
#define LG_M_WORRIED        "Волнение"

#define LG_MOOD_TEXT        "Текст настроения"
#endif //RU

///////////////////////////////////////////////////////////////////////////////////////////
//
//    Ukrainian : Недоработан!
//
///////////////////////////////////////////////////////////////////////////////////////////
#ifdef LANG_UA
#define LG_SELECT           "Вибір"
#define LG_BACK             "Назад"
#define LG_OK               "Добре"
#define LG_CLOSE            "Закрити"
#define LG_MENU             "Меню"
#define LG_CANCEL           "Відмінити"
#define LG_EXIT             "Вихід"
#define LG_HELP             "Допомога"
#define LG_UPDATE           "Оновити"
//status_schange.c
#define LG_STATUSSEL        "Вибір статусу"
#define LG_STONLINE         "В мережі"
#define LG_STCHAT           "Готовий до розмови"
#define LG_STAWAY           "Відсутній"
#define LG_STXA             "Недоступний"
#define LG_STDND            "Зайнятий"
#define LG_STINVIS          "Невидимий"
#define LG_STOFFLINE        "Оффлайн"
#define LG_STATUS           "Статус"
#define LG_ENTERTEXTSTATUS  "Введіть текст статусу:"
#define LG_PRIORITY         "Приоритет:"
//MUC_Enter_UI.c
#define LG_NONAMECONF       "Им'я конференції не заповнено!"
#define LG_ENTERMUC         "Вхід в MUC"
#define LG_NAMEMUC          "Им'я конференції:"
#define LG_NICK             "Нік:"
#define LG_GETMESSAGECOUNT  "Отримати повідомлень:"
#define LG_ENTER            "Увійти"
//message_list.c
#define LG_NOSENDNULLMESS   "Не можна відіслати порожнє повідомлення!"
#define LG_NEW              "Нове..."
//message_cmds.c
#define LG_SELCOMMAND       "Вибір команди..."
#define LG_SELTEMPLATE      "Вибір шаблону..."
#define LG_SELSMILE         "Вибір смайлу..."
#define LG_SELECT2          "Вибір..."
#define LG_CONTRESOURCES    "Ресурси..."
#define LG_CONTRESOURCE     "Ніки"
#define LG_COMMANDS         "Команди"
#define LG_MSGTEMPLATE      "Шаблони повідомлень"
#define LG_SMILE            "Смайли"
#define LG_CLOSEDLG         "Закрити діалог"
//mainmenu.c
#define LG_CONTACT          "Контакт"
#define LG_STATUS           "Статус"
#define LG_MUC              "Конференція"
#define LG_BOOKMARK         "Закладки"
#define LG_MVIBRA           "Режим вібри"
#define LG_MSOUND           "Режим звуку"
#define LG_MOFFLINE         "Офф. контакти"
#define LG_PLAYER_STATUS    "Плеер-статус"
#define LG_SETTINGS         "Налаштування"
#define LG_ABOUT            "Про эльф..."
#define LG_COLOR            "Кольори"
#define LG_ADDCONTACT       "Додати контакт"
#define LG_MOODS            "Настрій"
//main.c
#define LG_EXITSIEJC        "Покинути SieJC?"
#define LG_ZLIBNOSASL       "ZLib не працює без SASL!"
#define LG_ENTERLOGPAS      "Введіть логін/пароль!"
#define LG_PLATFORMM        "Платформа не відповідає!"
#define LG_ASTARTED         "Вже виконується!"
//jabber_util.c
#define LG_MUCEXITDONE      "Вихід из MUC виконано!"
#define LG_VERINFO          "Version Info:\nName:%s\nVersion:%s\nOS:%s"
#define LG_TIMEINFO         "Time Info:\nUTC:%s\nTime Zone:%s\n:>%s"
#define LG_LASTACTIVMSG     "IDLE: %d d. %d hr. %d min. %d sec."
//item_info.c
#define LG_ITEMIHDR         "Контакт інфо"
#define LG_ELROSTER         "Елемент ростеру"
#define LG_OFFLORCONTTR     "Оффлайн або контакт із транспорту"
#define LG_MUCPART          "Учасник конференції"
#define LG_JTRANSP          "Данний контакт є транспортом Jabber"
#define LG_GROUPROSTER      "Група ростеру"
#define LG_RESOURCE         "Ресурс:"
#define LG_PRIORITY         "Приоритет:"
#define LG_REALJID          "Реальний JID:"
#define LG_STATUS2          "Статус:"
#define LG_PRIVILEGES       "Привілеї:"
#define LG_ROLE             "Роль:"
#define LG_POSIBLCLIENT     "Можливості клієнта:"
#define LG_MUCSABJECT       "Тема:"
#define LG_ISUBSCRIBE       "Авторизація:"
//history.c
#define LG_ERRORWH          "Помилка I/O #%u при запису історії!"
//cont_menu.c
#define LG_MENUCONTACT      "Меню контакту"
#define LG_UNKACTION        "Дія невідома або не підтримується!"
#define LG_ABANDON          "Покинути"
#define LG_MUC_ADMIN        "muc#admin"
#define LG_KIK              "Кік"
#define LG_BAN              "Бан"
#define LG_LVOISE           "Відняти голос"     
#define LG_GVOISE           "Дати голос"
#define LG_PARTICIPANT      "Відняти членство"
#define LG_MEMBER           "Дати членство"
#define LG_MODERATOR        "Дати модератора"
#define LG_MODERATOR_REMOVE "Відняти модератора"
#define LG_ADMIN            "Дати адміна"
#define LG_OWNER            "Дати власника"
#define LG_VERCLIENT        "Версія клієнту"
#define LG_INFOFDISC        "Інфо із Disco"
#define LG_ON               "Включити"
#define LG_OFF              "Відключити"
#define LG_NOSUPACTION      "Немає підтримуваних дій"
#define LG_OHISTORY         "Історія"
#define LG_QUERYTIME        "Час"
#define LG_QUERYVCARD       "vCard"
#define LG_QUERYLAST        "Last Activity"
#define LG_SUBSCR           "Авторизація"
#define LG_EDIT             "Змінити"
#define LG_MUCCLEAR         "Очистити повідомлення"
#define LG_SUBSCRIBE        "Запросити"
#define LG_SUBSCRIBED       "Дозволити"
#define LG_UNSUBSCRIBED     "Відхилити"
#define LG_UNSUBSCRIBE      "Видалити"
#define LG_REASON           "Причина"
//clist_util.c
#define LG_AUTHORREM        "Авторизація видалена!"
#define LG_AUTHORGRANTED    "Авторизація надана!"
#define LG_AUTHORCAME       "Прийшов запит на авторизацію"
#define LG_AUTHORDECLINE    "В авторизації відмовленно"

#define LG_MUCCROK          "Конференція створена успішно"
//bookmarks.c
#define LG_MENUBOOKMARK     "Меню закладок"
//config_data.c
#define LG_NO               "Ні"
#define LG_YES              "Так"
#define LG_DISABLED         "Відключити"
#define LG_ENABLED          "Включити"
#define LG_SETUPCONECT      "Налаштування підключення"
#define LG_LOGIN            "Логін"
#define LG_PASSWORD         "Пароль"
#define LG_SERVER           "Сервер"
#define LG_HOST             "Хост"
#define LG_HOSTTYPE         "Тип хосту"
#define LG_HOSTNAME         "Им'я"
#define LG_IPADRESS         "IP адреса"
#define LG_PORT             "Порт"
#define LG_AUTHTYPE         "Авторизація"
#define LG_ZLIBUSE          "Використання ZLib"
#define LG_RES              "Ресурс"
#define LG_HISTORY          "Історія"
#define LG_MUCHIST          "MUC історія"
#define LG_MUCDEF           "MUC за умовчанням"
#define LG_MUCDEFMSGCOUNT   "Кіл. отриманих повідомлень"
#define LG_MUCDEFNIK        "Нік за умовчанням"
#define LG_SHOWIDLEICON     "Показувати значок на idle"
#define LG_IDLEICON         "Розташування значка"
#define LG_POPUPDIS         "Відображати POPUP"
#define LG_COMPOSEV         "Події повідомлень"
#define LG_DELIVREP         "Звіт о отриманні, якщо потрібно"
#define LG_USEATTENTION     "Приймати сигнал 'Attention'"
#define LG_FIRST_LETTER     "Перша літера заголовна"
#define LG_AUTO_JOIN        "Автовхід в конференцію"

#define LG_SETUPSND         "Налаштування звуку"
#define LG_SETUPVIBRPWR     "Потужність вібри"
#define LG_SNDVOL           "Гучність"
#define LG_SNDMSGSND        "Звук відправки"
#define LG_SNDMSGMUC        "Звук прийому із MUC"
#define LG_SNDMSGPM         "Звук прийому із PM"
#define LG_SNDONLINE        "Звук статуса онлайн"
#define LG_SNDOFFLINE       "Звук статуса оффлайн"
#define LG_SNDCOMPOSING     "Звук composing-повідомлень"

#define LG_SETUPPATH        "Налаштування шляхів"
#define LG_PATHHIST         "Історія"
#define LG_PATHPIC          "Картинки"
#define LG_PATHAVATARS      "Аватары"
#define LG_PATHCMD          "Команди"
#define LG_PATHMESG         "Повідомлення"
#define LG_PATHKNOWF        "Відомі особливості"
#define LG_PATHSMILECFG     "Конфіг смайлів"
#define LG_PATHSMILEDIR     "Каталог смайлів"
#define LG_DEFAULTDISK      "Диск за умовчанням"
#define LG_COLORPATH        "Каталог кол. схем"

#define LG_TEXTSTATUS       "Текст статусів"
#define LG_DEFSTATES        "Стани за умовчанням"

#define LG_VIEW             "Вигляд"
#define LG_ROSTER_FONT      "Шрифт ростеру"
#define LG_CHATS_FONT       "Шрифт списку повідомлень"
#define LG_SMALL_NORMAL_FONT "Малий"
#define LG_SMALL_BOLD_FONT  "Малий жирний"
#define LG_MID_NORMAL_FONT  "Середній"
#define LG_MID_BOLD_FONT    "Середній жирний"
#define LG_LARGE_NORMAL_FONT "Великий"
#define LG_LARGE_BOLD_FONT  "Великий жирний"
#define LG_UNDERLINING      "Підкреслення повідомлень"
#define LG_KBD_LAYOUT       "\"Разкладка\" клавіатури"
#define LG_KBD1             "Разкладка 1"
#define LG_KBD2             "Разкладка 2"
#define LG_SKROLL           "Скролінг"

#define LG_AUTOSTATUS       "Автостатус"
#define LG_AS_ENABLED       "Включений"
#define LG_AS_TIME          "Час (в хвилинах)"
#define LG_AS_TEXT          "Текст"

#ifdef ICONBAR
#define LG_ICONBAR_SI       "Показувати іконку в IconBar"
#define LG_ICONSET_FILENAME "Им'я файла з номерами іконок"
#endif
//vCard.c
#define LG_SHOW_AVATAR      "Показать аватару"

#define LG_VCARD_JABBERID   "JID"
#define LG_VCARD_FN         "Повне ім'я"
#define LG_VCARD_NICKNAME   "Нік"
#define LG_VCARD_N_FAMILY   "Фамілія"
#define LG_VCARD_N_GIVEN    "Им'я"
#define LG_VCARD_N_MIDDLE   "По батькові"
#define LG_VCARD_N_PREFIX   "LG_VCARD_N_PREFIX"
#define LG_VCARD_N_SUFFIX   "LG_VCARD_N_SUFFIX"
#define LG_VCARD_BDAY       "День народження"
#define LG_VCARD_GENDER     "Стать"
#define LG_VCARD_ORGNAME    "Назва організації"
#define LG_VCARD_ORGUNIT    "Відділ організації"
#define LG_VCARD_TITLE      "Назва посади"
#define LG_VCARD_ROLE       "Посада"

#define LG_VCARD_EMAIL      "E-Mail"
#define LG_VCARD_EMAIL_HOME          "EMAIL_HOME"
#define LG_VCARD_EMAIL_WORK          "EMAIL_WORK"
#define LG_VCARD_EMAIL_INTERNET      "EMAIL_INTERNET"
#define LG_VCARD_EMAIL_PREF          "EMAIL_PREF"
#define LG_VCARD_EMAIL_X400          "EMAIL_X400"

#define LG_VCARD_TEL_HOME   "LG_VCARD_TEL_HOME"
#define LG_VCARD_TEL_WORK   "LG_VCARD_TEL_WORK"
#define LG_VCARD_TEL_VOICE  "LG_VCARD_TEL_VOICE"
#define LG_VCARD_TEL_FAX    "LG_VCARD_TEL_FAX"
#define LG_VCARD_TEL_PAGER  "LG_VCARD_TEL_PAGER"
#define LG_VCARD_TEL_MSG    "LG_VCARD_TEL_MSG"
#define LG_VCARD_TEL_CELL   "LG_VCARD_TEL_CELL"
#define LG_VCARD_TEL_VIDEO  "LG_VCARD_TEL_VIDEO"
#define LG_VCARD_TEL_BBS    "LG_VCARD_TEL_BBS"
#define LG_VCARD_TEL_MODEM  "LG_VCARD_TEL_MODEM"
#define LG_VCARD_TEL_ISDN   "LG_VCARD_TEL_ISDN"
#define LG_VCARD_TEL_PCS    "LG_VCARD_TEL_PCS"
#define LG_VCARD_TEL_PREF   "LG_VCARD_TEL_PREF"
#define LG_VCARD_TEL_NUMBER "LG_VCARD_TEL_NUMBER"

#define LG_VCARD_ADR_HOME   "ADR_HOME"
#define LG_VCARD_ADR_WORK   "ADR_WORK"
#define LG_VCARD_ADR_POSTAL "ADR_POSTAL"
#define LG_VCARD_ADR_PARCEL "ADR_PARCEL"
#define LG_VCARD_ADR_DOM    "ADR_DOM"
#define LG_VCARD_ADR_PREF   "ADR_PREF"
#define LG_VCARD_ADR_POBOX  "ADR_POBOX"
#define LG_VCARD_ADR_EXTADD "ADR_EXTADD"
#define LG_VCARD_ADR_STREET "ADR_STREET"
#define LG_VCARD_ADR_LOCALITY "ADR_LOCALITY"
#define LG_VCARD_ADR_REGION          "Область"
#define LG_VCARD_ADR_PCODE           "Поштовий код"
#define LG_VCARD_ADR_CTRY            "Держава"
#define LG_VCARD_URL        "Домашня сторінка"
#define LG_VCARD_DESC       "Про себе"
#define LG_VCARD_TZ         "Часовий пояс"
#define LG_VCARD_AVATAR     "Аватара"
//jid_enter_ui
#define LG_JEDELCONTACT     "Видалити контакт:"
#define LG_JEASK            "Запросити підпис:"
#define LG_JEGROUP          "Група:"
#define LG_JENOJID          "JID відсутній!"
#define LG_JECONTACTHDR     "Контакт:"
//moods
#define LG_M_EMPTY          "Відсутній"
#define LG_M_AFRAID         "Переляканий"
#define LG_M_AMAZED         "Поразка"
#define LG_M_ANGRY          "Сердитий"
#define LG_M_ANNOYED        "Раздратований"
#define LG_M_ANXIOUS        "Стурбований"
#define LG_M_AROUSED        "Розбуджений"
#define LG_M_ASHAMED        "Присоромлений"
#define LG_M_BORED          "Нудьгуючий"
#define LG_M_BRAVE          "Хоробрий"
#define LG_M_CALM           "Спокійний"
#define LG_M_COLD           "Змерз"
#define LG_M_CONFUSED       "Збентежений"
#define LG_M_CONTENTED      "Задоволений"
#define LG_M_CRANKY         "Вагаюсь"
#define LG_M_CURIOUS        "Зацікавлений"
#define LG_M_DEPRESSED      "Пригноблений"
#define LG_M_DISAPPOINTED   "Розчаруваний"
#define LG_M_DISGUSTED      "Огида"
#define LG_M_DISTRACTED     "Розгублений"
#define LG_M_EMBARRASSED    "Сором'язливість"
#define LG_M_EXCITED        "Схвильований"
#define LG_M_FLIRTATIOUS    "Кокетлевий"
#define LG_M_FRUSTRATED     "Розбитий"
#define LG_M_GRUMPY         "Сердитий"
#define LG_M_GUILTY         "Винуватий"
#define LG_M_HAPPY          "Щасливий"
#define LG_M_HOT            "Гаряче"
#define LG_M_HUMBLED        "Принижений"
#define LG_M_HUMILIATED     "Ображений"
#define LG_M_HUNGRY         "Голодний"
#define LG_M_HURT           "Бешкетливий"
#define LG_M_IMPRESSED      "Вражений"
#define LG_M_IN_AWE         "Страх"
#define LG_M_IN_LOVE        "Закоханий"
#define LG_M_INDIGNANT      "Обурений"
#define LG_M_INTERESTED     "Зацікавлений"
#define LG_M_INTOXICATED    "Сп'янілий"
#define LG_M_INVINCIBLE     "Непереможний"
#define LG_M_JEALOUS        "Ревнивий"
#define LG_M_LONELY         "Самотній"
#define LG_M_MEAN           "Скупість"
#define LG_M_MOODY          "Вередливий"
#define LG_M_NERVOUS        "Нервовий"
#define LG_M_NEUTRAL        "Нейтральний"
#define LG_M_OFFENDED       "Ображений"
#define LG_M_PLAYFUL        "Грайливий"
#define LG_M_PROUD          "Гордий"
#define LG_M_RELIEVED       "Вільний"
#define LG_M_REMORSEFUL     "Розкаяння"
#define LG_M_RESTLESS       "Неспокійний"
#define LG_M_SAD            "Сумний"
#define LG_M_SARCASTIC      "Саркастичний"
#define LG_M_SERIOUS        "Серйозний"
#define LG_M_SHOCKED        "Шокований"
#define LG_M_SHY            "Полохливий"
#define LG_M_SICK           "Хворий"
#define LG_M_SLEEPY         "Сонний"
#define LG_M_STRESSED       "Стрес"
#define LG_M_SURPRISED      "Здивований"
#define LG_M_THIRSTY        "Спрага"
#define LG_M_WORRIED        "Хвилююсь"

#define LG_MOOD_TEXT        "Текст настрою"
#endif //UA

///////////////////////////////////////////////////////////////////////////////////////////
//
//    English : Недоработан!
//
///////////////////////////////////////////////////////////////////////////////////////////
#ifdef LANG_EN
#define LG_SELECT           "Select"
#define LG_BACK             "Back"
#define LG_OK               "OK"
#define LG_CLOSE            "Close"
#define LG_MENU             "Menu"
#define LG_CANCEL           "Cancel"
#define LG_EXIT             "Exit"
#define LG_HELP             "Help"
#define LG_UPDATE           "Update"
//status_schange.c
#define LG_STATUSSEL        "Status choice"
#define LG_STONLINE         "online"
#define LG_STCHAT           "chat"
#define LG_STAWAY           "away"
#define LG_STXA             "xa"
#define LG_STDND            "dnd"
#define LG_STINVIS          "invisible"
#define LG_STOFFLINE        "offline"
#define LG_STATUS           "Status"
#define LG_ENTERTEXTSTATUS  "Enter status text:"
#define LG_PRIORITY         "Priority:"
//MUC_Enter_UI.c
#define LG_NONAMECONF       "A conference name is empty!"
#define LG_ENTERMUC         "Join MUC"
#define LG_NAMEMUC          "MUC name:"
#define LG_NICK             "Nickname:"
#define LG_GETMESSAGECOUNT  "Number of messages:"
#define LG_ENTER            "To enter"
//message_list.c
#define LG_NOSENDNULLMESS   "It is impossible to send an empty message!"
#define LG_NEW              "New..."
//message_cmds.c
#define LG_SELCOMMAND       "Select command..."
#define LG_SELTEMPLATE      "Select template..."
#define LG_SELSMILE         "Select smile..."
#define LG_SELECT2          "Select..."
#define LG_CONTRESOURCES    "Resource..."
#define LG_CONTRESOURCE     "Nicknames"
#define LG_COMMANDS         "Commands"
#define LG_MSGTEMPLATE      "Templates"
#define LG_SMILE            "Smiles"
#define LG_CLOSEDLG         "Close"
//mainmenu.c
#define LG_CONTACT          "Contact"
#define LG_STATUS           "Status"
#define LG_MUC              "MUC"
#define LG_BOOKMARK         "Bookmarks"
#define LG_MVIBRA           "Vibra mode"
#define LG_MSOUND           "Sound mode"
#define LG_MOFFLINE         "Show Offline"
#define LG_PLAYER_STATUS    "Player-status"
#define LG_SETTINGS         "Settings"
#define LG_ABOUT            "About..."
#define LG_COLOR            "Colors"
#define LG_ADDCONTACT       "Add contact"
#define LG_MOODS            "User Moods"
//main.c
#define LG_EXITSIEJC        "Exit SieJC?"
#define LG_ZLIBNOSASL       "ZLib doesn't work without SASL!"
#define LG_ENTERLOGPAS      "Enter login/password!"
#define LG_PLATFORMM        "Target platform mismatch!"
#define LG_ASTARTED         "Already started"
//jabber_util.c
#define LG_MUCEXITDONE      "Leave MUC ok"
#define LG_VERINFO          "Version Info:\nName:%s\nVersion:%s\nOS:%s"
#define LG_TIMEINFO         "Time Info:\nUTC:%s\nTime Zone:%s\n:>%s"
#define LG_LASTACTIVMSG     "IDLE: %d d. %d hr. %d min. %d sec."
//item_info.c
#define LG_ITEMIHDR         "Contact Info"
#define LG_ELROSTER         "Roster elements"
#define LG_OFFLORCONTTR     "Offline or transport contact"
#define LG_MUCPART          "MUC partcipiant"
#define LG_JTRANSP          "This contact is a transport"
#define LG_GROUPROSTER      "Roster group"
#define LG_RESOURCE         "Resource:"
#define LG_PRIORITY         "Priority:"
#define LG_REALJID          "Real JID:"
#define LG_STATUS2          "Status:"
#define LG_PRIVILEGES       "Affiliation:"
#define LG_ROLE             "Role:"
#define LG_POSIBLCLIENT     "Client features:"
#define LG_MUCSABJECT       "Sabject:"
#define LG_ISUBSCRIBE       "Subscibe:"
//history.c
#define LG_ERRORWH          "I/O Error #%u while trying to write the history"
//cont_menu.c
#define LG_MENUCONTACT      "Contact menu"
#define LG_UNKACTION        "Unknown or unsupported action!"
#define LG_ABANDON          "Leave MUC"
#define LG_MUC_ADMIN        "muc#admin"
#define LG_KIK              "Kick"
#define LG_BAN              "Ban"
#define LG_LVOISE           "Revoke voice"
#define LG_GVOISE           "Grant voice"
#define LG_PARTICIPANT      "Unaffiliate"
#define LG_MEMBER           "Grant Membership"
#define LG_MODERATOR        "Grant Moderator"
#define LG_MODERATOR_REMOVE "Remove Moderator"
#define LG_ADMIN            "Grant Admin"
#define LG_OWNER            "Grant Ownership"
#define LG_VERCLIENT        "Version"
#define LG_INFOFDISC        "Disco info"
#define LG_ON               "Connect"
#define LG_OFF              "Disconnect"
#define LG_NOSUPACTION      "No supported action"
#define LG_OHISTORY         "History"
#define LG_QUERYTIME        "Time"
#define LG_QUERYVCARD       "vCard"
#define LG_QUERYLAST        "Last Activity"
#define LG_SUBSCR           "Subscription"
#define LG_EDIT             "Edit"
#define LG_MUCCLEAR         "Clear messages"
#define LG_SUBSCRIBE        "Ask"
#define LG_SUBSCRIBED       "Allow subscription"
#define LG_UNSUBSCRIBED     "Deny subscription"
#define LG_UNSUBSCRIBE      "Remove"
#define LG_REASON           "Reason"
//clist_util.c
#define LG_AUTHORREM        "Authorization was removed!"
#define LG_AUTHORGRANTED    "Authorization was granted!"
#define LG_AUTHORCAME       "Authorization request came"
#define LG_AUTHORDECLINE    "Authorization decline"

#define LG_MUCCROK          "MUC created OK!"
//bookmarks.c
#define LG_MENUBOOKMARK     "Bookmarks menu"
//config_data.c
#define LG_NO               "No"
#define LG_YES              "Yes"
#define LG_DISABLED         "Disabled"
#define LG_ENABLED          "Enabled"
#define LG_SETUPCONECT      "Connection setup"
#define LG_LOGIN            "Login"
#define LG_PASSWORD         "Password"
#define LG_SERVER           "Server"
#define LG_HOST             "Host"
#define LG_HOSTTYPE         "Host type"
#define LG_HOSTNAME         "Host name"
#define LG_IPADRESS         "IP address"
#define LG_PORT             "Port"
#define LG_AUTHTYPE         "Auth type"
#define LG_ZLIBUSE          "ZLib usage"
#define LG_RES              "Resource"
#define LG_HISTORY          "History"
#define LG_MUCHIST          "MUC history"
#define LG_MUCDEF           "Default MUC"
#define LG_MUCDEFMSGCOUNT   "MUC message count"
#define LG_MUCDEFNIK        "Default MUC nick"
#define LG_SHOWIDLEICON     "Show icon on idle screen"
#define LG_IDLEICON         "Idle icon position"
#define LG_POPUPDIS         "Display pop-ups"
#define LG_COMPOSEV         "Composing Events"
#define LG_DELIVREP         "Delivery Report if required"
#define LG_USEATTENTION     "Recive command 'Attention'"
#define LG_FIRST_LETTER     "Big first letter"
#define LG_AUTO_JOIN        "MUC auto join"

#define LG_SETUPSND         "Sounds setup"
#define LG_SETUPVIBRPWR     "Vibra power"
#define LG_SNDVOL           "Sound Volume"
#define LG_SNDMSGSND        "Sound Msg Send"
#define LG_SNDMSGMUC        "Sound Msg Conf"
#define LG_SNDMSGPM         "Sound Msg PM"
#define LG_SNDONLINE        "Sound for online-status"
#define LG_SNDOFFLINE       "Sound for offline-status"
#define LG_SNDCOMPOSING     "Sound for composing-events"

#define LG_SETUPPATH        "Paths setup"
#define LG_PATHHIST         "History path"
#define LG_PATHPIC          "Pictures path"
#define LG_PATHAVATARS      "Avatars path"
#define LG_PATHCMD          "Commands path"
#define LG_PATHMESG         "Messages path"
#define LG_PATHKNOWF        "Known features"
#define LG_PATHSMILECFG     "Smiles config"
#define LG_PATHSMILEDIR     "Smiles .png path"
#define LG_DEFAULTDISK      "Default disc"
#define LG_COLORPATH        "Color schemes path"

#define LG_TEXTSTATUS       "Statuses text"
#define LG_DEFSTATES        "Default states"

#define LG_VIEW             "View"
#define LG_ROSTER_FONT      "Roster font"
#define LG_CHATS_FONT       "Messagelist font"
#define LG_SMALL_NORMAL_FONT "Small"
#define LG_SMALL_BOLD_FONT  "Small bold"
#define LG_MID_NORMAL_FONT  "Medium"
#define LG_MID_BOLD_FONT    "Medium bold"
#define LG_LARGE_NORMAL_FONT "Large"
#define LG_LARGE_BOLD_FONT  "Large bold"
#define LG_UNDERLINING      "Underline messages"
#define LG_KBD_LAYOUT       "Keyboard \"layout\""
#define LG_KBD1             "Layout 1"
#define LG_KBD2             "Layout 2"
#define LG_SKROLL           "SCROLL"

#define LG_AUTOSTATUS       "Autostatus"
#define LG_AS_ENABLED       "Enable"
#define LG_AS_TIME          "Time (minutes)"
#define LG_AS_TEXT          "Text"

#ifdef ICONBAR
#define LG_ICONBAR_SI       "Show icon in IconBar"
#define LG_ICONSET_FILENAME "File name with icon numbers"
#endif
//vCard.c
#define LG_SHOW_AVATAR      "Show avatar"

#define LG_VCARD_JABBERID   "JID"
#define LG_VCARD_FN         "Full name"
#define LG_VCARD_NICKNAME   "Nickname"
#define LG_VCARD_N_FAMILY   "LG_VCARD_N_FAMILY"
#define LG_VCARD_N_GIVEN    "LG_VCARD_N_GIVEN"
#define LG_VCARD_N_MIDDLE   "LG_VCARD_N_MIDDLE"
#define LG_VCARD_N_PREFIX   "LG_VCARD_N_PREFIX"
#define LG_VCARD_N_SUFFIX   "LG_VCARD_N_SUFFIX"
#define LG_VCARD_BDAY       "Birthday"
#define LG_VCARD_GENDER     "Gender"
#define LG_VCARD_ORGNAME    "Org. name"
#define LG_VCARD_ORGUNIT    "Org. unit"
#define LG_VCARD_TITLE      "Title"
#define LG_VCARD_ROLE       "Role"

#define LG_VCARD_EMAIL      "E-Mail"
#define LG_VCARD_EMAIL_HOME          "EMAIL_HOME"
#define LG_VCARD_EMAIL_WORK          "EMAIL_WORK"
#define LG_VCARD_EMAIL_INTERNET      "EMAIL_INTERNET"
#define LG_VCARD_EMAIL_PREF          "EMAIL_PREF"
#define LG_VCARD_EMAIL_X400          "EMAIL_X400"

#define LG_VCARD_TEL_HOME   "LG_VCARD_TEL_HOME"
#define LG_VCARD_TEL_WORK   "LG_VCARD_TEL_WORK"
#define LG_VCARD_TEL_VOICE  "LG_VCARD_TEL_VOICE"
#define LG_VCARD_TEL_FAX    "LG_VCARD_TEL_FAX"
#define LG_VCARD_TEL_PAGER  "LG_VCARD_TEL_PAGER"
#define LG_VCARD_TEL_MSG    "LG_VCARD_TEL_MSG"
#define LG_VCARD_TEL_CELL   "LG_VCARD_TEL_CELL"
#define LG_VCARD_TEL_VIDEO  "LG_VCARD_TEL_VIDEO"
#define LG_VCARD_TEL_BBS    "LG_VCARD_TEL_BBS"
#define LG_VCARD_TEL_MODEM  "LG_VCARD_TEL_MODEM"
#define LG_VCARD_TEL_ISDN   "LG_VCARD_TEL_ISDN"
#define LG_VCARD_TEL_PCS    "LG_VCARD_TEL_PCS"
#define LG_VCARD_TEL_PREF   "LG_VCARD_TEL_PREF"
#define LG_VCARD_TEL_NUMBER "LG_VCARD_TEL_NUMBER"

#define LG_VCARD_ADR_HOME   "ADR_HOME"
#define LG_VCARD_ADR_WORK   "ADR_WORK"
#define LG_VCARD_ADR_POSTAL "ADR_POSTAL"
#define LG_VCARD_ADR_PARCEL "ADR_PARCEL"
#define LG_VCARD_ADR_DOM    "ADR_DOM"
#define LG_VCARD_ADR_PREF   "ADR_PREF"
#define LG_VCARD_ADR_POBOX  "ADR_POBOX"
#define LG_VCARD_ADR_EXTADD "ADR_EXTADD"
#define LG_VCARD_ADR_STREET "ADR_STREET"
#define LG_VCARD_ADR_LOCALITY   "ADR_LOCALITY"
#define LG_VCARD_ADR_REGION "Region(state)"
#define LG_VCARD_ADR_PCODE  "Post code"
#define LG_VCARD_ADR_CTRY   "Country"
#define LG_VCARD_URL        "Homepage"
#define LG_VCARD_DESC       "Description"
#define LG_VCARD_TZ         "Time zone"
#define LG_VCARD_AVATAR     "Avatar"
//jid_enter_ui
#define LG_JEDELCONTACT     "Delete contact:"
#define LG_JEASK            "Ask subscribe:"
#define LG_JEGROUP          "Group:"
#define LG_JENOJID          "No JID!"
#define LG_JECONTACTHDR     "Contact:"
//moods
#define LG_M_EMPTY         "Null"
#define LG_M_AFRAID         "Afraid"
#define LG_M_AMAZED         "Amazed"
#define LG_M_ANGRY          "Angry"
#define LG_M_ANNOYED        "Annoyed"
#define LG_M_ANXIOUS        "Anxious"
#define LG_M_AROUSED        "Aroused"
#define LG_M_ASHAMED        "Ashamed"
#define LG_M_BORED          "Bored"
#define LG_M_BRAVE          "Brave"
#define LG_M_CALM           "Calm"
#define LG_M_COLD           "Cold"
#define LG_M_CONFUSED       "Confused"
#define LG_M_CONTENTED      "Contented"
#define LG_M_CRANKY         "Cranky"
#define LG_M_CURIOUS        "Curious"
#define LG_M_DEPRESSED      "Depressed"
#define LG_M_DISAPPOINTED   "Disappointed"
#define LG_M_DISGUSTED      "Disgusted"
#define LG_M_DISTRACTED     "Distracted"
#define LG_M_EMBARRASSED    "Embarrassed"
#define LG_M_EXCITED        "Excited"
#define LG_M_FLIRTATIOUS    "Flirtatious"
#define LG_M_FRUSTRATED     "Frustrated"
#define LG_M_GRUMPY         "Grumpy"
#define LG_M_GUILTY         "Cuilty"
#define LG_M_HAPPY          "Happy"
#define LG_M_HOT            "Hot"
#define LG_M_HUMBLED        "Humbled"
#define LG_M_HUMILIATED     "Humiliated"
#define LG_M_HUNGRY         "Hungry"
#define LG_M_HURT           "Hurt"
#define LG_M_IMPRESSED      "Impressed"
#define LG_M_IN_AWE         "In awe"
#define LG_M_IN_LOVE        "In love"
#define LG_M_INDIGNANT      "Indignant"
#define LG_M_INTERESTED     "Interested"
#define LG_M_INTOXICATED    "Intoxicated"
#define LG_M_INVINCIBLE     "Invincible"
#define LG_M_JEALOUS        "Jealous"
#define LG_M_LONELY         "Lonely"
#define LG_M_MEAN           "Mean"
#define LG_M_MOODY          "Moody"
#define LG_M_NERVOUS        "Nervous"
#define LG_M_NEUTRAL        "Neutral"
#define LG_M_OFFENDED       "Offended"
#define LG_M_PLAYFUL        "Playful"
#define LG_M_PROUD          "Proud"
#define LG_M_RELIEVED       "Relieved"
#define LG_M_REMORSEFUL     "Remorseful"
#define LG_M_RESTLESS       "Restless"
#define LG_M_SAD            "Sad"
#define LG_M_SARCASTIC      "Sarcastic"
#define LG_M_SERIOUS        "Serious"
#define LG_M_SHOCKED        "Shocked"
#define LG_M_SHY            "Shy"
#define LG_M_SICK           "Sick"
#define LG_M_SLEEPY         "Sleepy"
#define LG_M_STRESSED       "Stressed"
#define LG_M_SURPRISED      "Surprised"
#define LG_M_THIRSTY        "Thirsty"
#define LG_M_WORRIED        "Worried"

#define LG_MOOD_TEXT        "Mood text"
#endif //EN
#endif
