#ifndef _LANG_H_
#define _LANG_H_

#define ELFNAME		"Master.elf"
#define COPYRIGHT	"Master.elf\n(c) BingK(binghelingxi)\n(r) all the author of CfgEdit!"

#define LANG_CN
//#define LANG_EN

#ifdef LANG_CN

#define ERR_STR			"Îøèáêà!"
#define LGP_EXIT		"Âûõîä"
#define LGP_SELECT		"Âûáîğ"
#define LGP_MENU		"Ìåíş"
#define LGP_OPTIONS		"Îïöèè"
#define LGP_ONOFF		"Âêë/Âûêë"
#define LGP_QUIT		"Âûõîä"
#define LGP_ABOUT		"Îïèñàíèå..."
#define LGP_NOTSUPPORT	"Íå ïîääåğæèâàåòñÿ"
#define LGP_ENTER		"Enter"
#define LGP_CBOX_ERR	"´íÎóµÄÑ¡Ïî"
#define LGP_OK			"Íê³É"
#define	LGP_BACK		"·µ»Ø"
#define LGP_CLOSE		"¹Ø±Õ"
#define LGP_SELECT_FILE	"Ñ¡ÔñÎÄ¼ş"
#define LGP_SELECT_FOLDER	"Ñ¡ÔñÎÄ¼ş¼Ğ"
#define LGP_PROFILE		"Çé¾°Ä£Ê½"
/*#define LGP_PROFILE1	"Çé¾°Ä£Ê½1"
#define LGP_PROFILE2	"Çé¾°Ä£Ê½2"
#define LGP_PROFILE3	"Çé¾°Ä£Ê½3"
#define LGP_PROFILE4	"Çé¾°Ä£Ê½4"
#define LGP_PROFILE5	"Çé¾°Ä£Ê½5"
#define LGP_PROFILE6	"Çé¾°Ä£Ê½6"
#define LGP_PROFILE7	"Çé¾°Ä£Ê½7"*/
#define LGP_DEL_ALL		"Çå³ıËùÓĞÅäÖÃ"
#define LGP_RELOAD_CONFIG_ERR	"ÖØĞÂ¶ÁÈ¡ÅäÖÃÊ§°Ü!"
#define LGP_DEL_THIS	"Çå³ı¸Ã²¹¶¡ÅäÖÃ"
#define LGP_DEL_UNUSED	"Çå³ıÎŞÓÃÅäÖÃ"
#define LGP_PATCH_NAME	"²¹¶¡:"
#define LGP_PATCH_AUTHOR	"×÷Õß:"
#define LGP_PATCH_ID	"ID:"
#define LGP_PATCH_VERSION	"°æ±¾:"
#define LGP_PATCH_INFO_OTH	"ÆäËüĞÅÏ¢:"
#define LGP_PATCH_INFO	"²¹¶¡ĞÅÏ¢"
#define LGP_BACKUP		"±¸·İÅäÖÃ"
#define LGP_RESTORE		"»Ö¸´±¸·İ"
#define LGP_BACKUP_PATH "±¸·İÎÄ¼şÂ·¾¶:"
#define LGP_RESTORE_PATH	"»Ö¸´±¸·İÂ·¾¶:"
#define LGP_ENTER_PATH	"ÊäÈëÎÄ¼ş¼ĞÂ·¾¶"
#define LGP_IS_OFF		"ÒÑ¹Ø±Õ"
#define	LGP_QUIT_WITHOUT_RS	"²»Ë¢ĞÂMPÍË³ö"
#endif

#ifdef LANG_EN
#define ERR_STR			"Error!"
#define LGP_EXIT		"Exit"
#define LGP_SELECT		"Select"
#define LGP_MENU		"Menu"
#define LGP_OPTIONS		"Options"
#define LGP_ONOFF		"On/Off"
#define LGP_QUIT		"Quit"
#define LGP_ABOUT		"About..."
#define LGP_NOTSUPPORT	"ItemNotSupported"
#define LGP_ENTER		"Enter"
#define LGP_CBOX_ERR	"ChoiceIndexError!"
#define LGP_OK			"OK"
#define	LGP_BACK		"Back"
#define LGP_CLOSE		"Close"
#define LGP_SELECT_FILE	"Select File"
#define LGP_SELECT_FOLDER	"Select Folder"
#define LGP_PROFILE		"Profile"
/*#define LGP_PROFILE1	"Profile1"
#define LGP_PROFILE2	"Profile2"
#define LGP_PROFILE3	"Profile3"
#define LGP_PROFILE4	"Profile4"
#define LGP_PROFILE5	"Profile5"
#define LGP_PROFILE6	"Profile6"
#define LGP_PROFILE7	"Profile7"*/
#define LGP_DEL_ALL		"Clear All Configs"
#define LGP_RELOAD_CONFIG_ERR	"Reload Config Error!"
#define LGP_DEL_THIS	"Clear This Config"
#define LGP_DEL_UNUSED	"Clear Unused Configs"
#define LGP_PATCH_NAME	"Name:"
#define LGP_PATCH_AUTHOR	"Author:"
#define LGP_PATCH_ID	"ID:"
#define LGP_PATCH_VERSION	"Version:"
#define LGP_PATCH_INFO_OTH	"Other Info:"
#define LGP_PATCH_INFO	"Info"
#define LGP_BACKUP		"Backup Configs"
#define LGP_RESTORE		"Restore Configs"
#define LGP_BACKUP_PATH "Backup Path:"
#define LGP_RESTORE_PATH	"Restore Path:"
#define LGP_ENTER_PATH	"Enter Folder Path"
#define LGP_IS_OFF		"Is Off"
#define	LGP_QUIT_WITHOUT_RS	"Quit Without RunScaner"
#endif
#endif
