#define IPC_SPLAYER_NAME    "SPlayer"
#define IPC_GRANTEE_NAME    "Grantee"
#define IPC_CONTROL_NAME    "Control"
#define IPC_EDITOR_NAME     "Editor"
#define IPC_CHECK_DOUBLERUN 1
#define IPC_PLAY_PAUSE      2
#define IPC_STOP            3
#define IPC_NEXT_TRACK      4
#define IPC_PREV_TRACK      5
#define IPC_REFRESH         6
#define IPC_SPLAYER_STARTED 0xF
#define IPC_SPLAYER_CLOSED  0x0
