/*
    SieNatJabber Project
 Language
*/
#include "setlang.h"
#ifndef _LANG_H_
#define _LANG_H_

#define LG_COPYRIGHT "Siemens natJabber Client\n(c)Kibab, Ad, Borman99\n%s r%i\nCompiled %s"

///////////////////////////////////////////////////////////////////////////////////////////
//
//    Russian : Недоработан!
//
///////////////////////////////////////////////////////////////////////////////////////////
#ifdef LANG_RU
#define LG_SELECT           "Выбор"
#define LG_BACK             "Назад"
#define LG_OK               "OK"
#define LG_CLOSE            "Закрыть"
#define LG_MENU             "Меню"
#define LG_CANCEL           "Отмена"
#define LG_EXIT             "Выход"
#define LG_HELP             "Помощь"
#define LG_UPDATE           "Обновить"
//status_schange.c
#define LG_STATUSSEL        "Выбор статуса"
#define LG_STONLINE         "Онлайн"
#define LG_STCHAT           "Готов болтать"
#define LG_STAWAY           "Отсутствую"
#define LG_STXA             "Недоступен"
#define LG_STDND            "Занят"
#define LG_STINVIS          "Инвиз"
#define LG_STOFFLINE        "Оффлайн"
#define LG_STATUS           "Статус"
#define LG_ENTERTEXTSTATUS  "Введите текст статуса:"
#define LG_PRIORITY         "Приоритет:"
//MUC_Enter_UI.c
#define LG_NONAMECONF       "Имя конфы не заполнено!"
#define LG_ENTERMUC         "Вход в MUC"
#define LG_NAMEMUC          "Имя конференции:"
#define LG_NICK             "Ник:"
#define LG_GETMESSAGECOUNT  "Получить сообщений:"
//message_list.c
#define LG_NOSENDNULLMESS   "Нельзя послать пустое сообщение!"
#define LG_NEW              "Новое..."
//message_cmds.c
#define LG_SELCOMMAND       "Выбор команды..."
#define LG_SELTEMPLATE      "Выбор шаблона..."
#define LG_SELSMILE         "Выбор смайла..."
#define LG_SELECT2          "Выбор..."
#define LG_CONTRESOURCES    "Ресурсы..."  //както подругому надо
#define LG_CONTRESOURCE     "Ники"
#define LG_COMMANDS         "Команды"
#define LG_MSGTEMPLATE      "Шаблоны сообщений"
#define LG_SMILE            "Смайлы"
#define LG_CLOSEDLG         "Закрыть диалог"
//mainmenu.c
#define LG_CONTACT          "Контакт"
#define LG_STATUS           "Статус"
#define LG_MUC              "Конференция"
#define LG_BOOKMARK         "Закладки"
#define LG_MVIBRA           "Режим вибры"
#define LG_MSOUND           "Режим звука"
#define LG_MOFFLINE         "Офф. контакты"
#define LG_SETTINGS         "Настройки"
#define LG_ABOUT            "Об эльфе..."
#define LG_COLOR            "Цвета"
#define LG_ADDCONTACT       "Добавить контакт"
#define LG_PLAYERSTATUS     "PlayerStatus"
//main.c
#define LG_EXITSIEJC        "Покинуть SieJC?"
#define LG_ZLIBNOSASL       "ZLib не работает без SASL!"
#define LG_ENTERLOGPAS      "Введите логин/пароль!"
#define LG_PLATFORMM        "Платформа не соответствует!"
#define LG_ASTARTED         "Уже запущен"
//jabber_util.c
#define LG_MUCEXITDONE      "Выход из MUC выполнен!"
#define LG_VERINFO          "Version Info:\nName:%s\nVersion:%s\nOS:%s"
#define LG_TIMEINFO         "Time Info:\nUTC:%s\nTime Zone:%s\n:>%s"
#define LG_LASTACTIVMSG     "IDLE: %d d. %d hr. %d min. %d sec." //почемуто кирилица вызывает Bad UTF encoding..
//item_info.c
#define LG_ITEMIHDR         "Контакт инфо"
#define LG_ELROSTER         "Элемент ростера"
#define LG_OFFLORCONTTR     "Оффлайн или контакт из транспорта"
#define LG_MUCPART          "Участник конференции"
#define LG_JTRANSP          "Данный контакт является транспортом Jabber"
#define LG_GROUPROSTER      "Группа ростера"
#define LG_RESOURCE         "Ресурс:"
#define LG_PRIORITY         "Приоритет:"
#define LG_REALJID          "Реальный JID:"
#define LG_STATUS2          "Статус:"
#define LG_PRIVILEGES       "Привилегии:"
#define LG_ROLE             "Роль:"
#define LG_POSIBLCLIENT     "Возможности клиента:"
#define LG_MUCSABJECT       "Тема:"
//#define LG_MUCNICK          "Ник:"
#define LG_ISUBSCRIBE       "Авторизация:"
//history.c
#define LG_ERRORWH          "Ошибка I/O #%u при записи истории!"
//cont_menu.c
#define LG_MENUCONTACT      "Меню контакта"
#define LG_UNKACTION        "Действие неизвестно или не поддерживается!"
#define LG_ABANDON          "Покинуть"
#define LG_MUC_ADMIN        "muc#admin"
#define LG_KIK              "Кик"
#define LG_BAN              "Бан"
#define LG_LVOISE           "Отнять голос"
#define LG_GVOISE           "Дать голос"
#define LG_PARTICIPANT      "Отнять членство"
#define LG_MEMBER           "Дать членство"
#define LG_MODERATOR        "Дать модератора"
#define LG_MODERATOR_REMOVE "Отнять модератора"
#define LG_ADMIN            "Дать админа"
#define LG_OWNER            "Дать владельца"
#define LG_VERCLIENT        "Версия клиента"
#define LG_INFOFDISC        "Инфо из Disco"
#define LG_ON               "Включить"
#define LG_OFF              "Отключить"
#define LG_NOSUPACTION      "Нет поддерживаемых действий"
#define LG_OHISTORY         "История"
#define LG_QUERYTIME        "Время клиента"
#define LG_QUERYVCARD       "vCard"
#define LG_QUERYLAST        "Бездействие"
#define LG_SUBSCR           "Подписка"
#define LG_EDIT             "Изменить"
#define LG_MUCCLEAR         "Очистить сообщения"
#define LG_SUBSCRIBE        "Запросить"
#define LG_SUBSCRIBED       "Разрешить"
#define LG_UNSUBSCRIBED     "Отклонить"
#define LG_UNSUBSCRIBE      "Удалить"
#define LG_REASON           "Причина"

//clist_util.c
#define LG_AUTHORREM        "В авторизации отказано!"
#define LG_AUTHORGRANTED    "Авторизация дана!"
#define LG_MUCCROK          "Конференция создана успешно"
//bookmarks.c
#define LG_MENUBOOKMARK     "Меню закладок"
//config_data.c
#define LG_NO               "Нет"
#define LG_YES              "Да"
#define LG_DISABLED         "Отключить"
#define LG_ENABLED          "Включить"

#define LG_SETUPCONECT      "Настройка подключения"
#define LG_LOGIN            "Логин"
#define LG_PASSWORD         "Пароль"
#define LG_SERVER           "Сервер"
#define LG_HOST             "Хост"
#define LG_HOSTTYPE         "Тип хоста"
#define LG_HOSTNAME         "Имя"
#define LG_IPADRESS         "IP адрес"
#define LG_PORT             "Порт"
#define LG_AUTHTYPE         "Авторизация"
#define LG_ZLIBUSE          "Использование ZLib"
#define LG_RES              "Ресурс"
#define LG_HISTORY          "История"
#define LG_MUCHIST          "MUC история"
#define LG_MUCDEF           "MUC по умолчанию"
#define LG_MUCDEFMSGCOUNT   "Кол. загружаемых сообщений"
#define LG_MUCDEFNIK        "Ник по умолчанию"
#define LG_IDLEICON         "Положение значка"
#define LG_POPUPDIS         "Отображать POPUP"
#define LG_COMPOSEV         "События сообщений"
#define LG_DELIVREP         "Отчет о доставке, если требуется"

#define LG_SETUPSND         "Настройка звука"
#define LG_SNDVOL           "Громкость"
#define LG_SNDMSGSND        "Звук отправки"
#define LG_SNDMSGMUC        "Звук приема из MUC"
#define LG_SNDMSGPM         "Звук приема из PM"
#define LG_SNDONLINE        "Звук статуса онлайн"
#define LG_SNDOFFLINE       "Звук статуса оффлайн"
#define LG_SNDCOMPOSING     "Звук composing-событий"

#define LG_SETUPPATH        "Настройка путей"
#define LG_PATHHIST         "История"
#define LG_PATHPIC          "Картинки"
#define LG_PATHAVATARS      "Аватары"
#define LG_PATHCMD          "Команды"
#define LG_PATHMESG         "Сообщения"
#define LG_PATHKNOWF        "Известные возможности"
#define LG_PATHSMILECFG     "Конфиг смайлов"
#define LG_PATHSMILEDIR     "Каталог смайлов"
#define LG_DEFAULTDISK      "Диск по умолчанию"

#define LG_TEXTSTATUS       "Текст статусов"
#define LG_DEFSTATES        "Состояния по умолчанию"

#define LG_VIEW             "Вид"
#define LG_ROSTER_FONT      "Шрифт ростера"
#define LG_CHATS_FONT       "Шрифт списка сообщений"
#define LG_SMALL_NORMAL_FONT "Маленький"
#define LG_SMALL_BOLD_FONT  "Маленький жирный"
#define LG_MID_NORMAL_FONT  "Средний"
#define LG_MID_BOLD_FONT    "Средний жирный"
#define LG_LARGE_NORMAL_FONT "Большой"
#define LG_LARGE_BOLD_FONT  "Большой жирный"
#define LG_UNDERLINING      "Подчеркивание сообщений"

#define LG_KBD_LAYOUT       "\"Раскладка\" клавиатуры"
#define LG_KBD1             "Раскладка 1"
#define LG_KBD2             "Раскладка 2"
#define LG_SKROLL           "СКРОЛЛИНГ"

#define LG_AUTOSTATUS       "Автостатус"
#define LG_AS_ENABLED       "Включен"
#define LG_AS_TIME          "Время (в минутах)"

//vCard.c
#define LG_SHOW_AVATAR      "Показать аватару"

#define LG_VCARD_JABBERID   "JID"
#define LG_VCARD_FN         "Полное имя"
#define LG_VCARD_NICKNAME   "Ник"
#define LG_VCARD_N_FAMILY   "Фамилия"
#define LG_VCARD_N_GIVEN    "Имя"
#define LG_VCARD_N_MIDDLE   "Отчество"
#define LG_VCARD_N_PREFIX   "N_PREFIX"
#define LG_VCARD_N_SUFFIX   "N_SUFFIX"
#define LG_VCARD_BDAY       "День рождения"
#define LG_VCARD_GENDER     "Пол"
#define LG_VCARD_ORGNAME    "Название организации"
#define LG_VCARD_ORGUNIT    "Отделение организации"
#define LG_VCARD_TITLE      "Название должности"
#define LG_VCARD_ROLE       "Должность"

#define LG_VCARD_EMAIL          "E-Mail"
#define LG_VCARD_EMAIL_HOME     "EMAIL_HOME"
#define LG_VCARD_EMAIL_WORK     "EMAIL_WORK"
#define LG_VCARD_EMAIL_INTERNET "EMAIL_INTERNET"
#define LG_VCARD_EMAIL_PREF     "EMAIL_PREF"
#define LG_VCARD_EMAIL_X400     "EMAIL_X400"

#define LG_VCARD_TEL_HOME   "TEL_HOME"
#define LG_VCARD_TEL_WORK   "TEL_WORK"
#define LG_VCARD_TEL_VOICE  "TEL_VOICE"
#define LG_VCARD_TEL_FAX    "TEL_FAX"
#define LG_VCARD_TEL_PAGER  "TEL_PAGER"
#define LG_VCARD_TEL_MSG    "TEL_MSG"
#define LG_VCARD_TEL_CELL   "TEL_CELL"
#define LG_VCARD_TEL_VIDEO  "TEL_VIDEO"
#define LG_VCARD_TEL_BBS    "TEL_BBS"
#define LG_VCARD_TEL_MODEM  "TEL_MODEM"
#define LG_VCARD_TEL_ISDN   "TEL_ISDN"
#define LG_VCARD_TEL_PCS    "TEL_PCS"
#define LG_VCARD_TEL_PREF   "TEL_PREF"
#define LG_VCARD_TEL_NUMBER "TEL_NUMBER"

#define LG_VCARD_ADR_HOME   "ADR_HOME"
#define LG_VCARD_ADR_WORK   "ADR_WORK"
#define LG_VCARD_ADR_POSTAL "ADR_POSTAL"
#define LG_VCARD_ADR_PARCEL "ADR_PARCEL"
#define LG_VCARD_ADR_DOM    "ADR_DOM"
#define LG_VCARD_ADR_PREF   "ADR_PREF"
#define LG_VCARD_ADR_POBOX  "ADR_POBOX"
#define LG_VCARD_ADR_EXTADD "ADR_EXTADD"
#define LG_VCARD_ADR_STREET "ADR_STREET"
#define LG_VCARD_ADR_LOCALITY "ADR_LOCALITY"
#define LG_VCARD_ADR_REGION   "Регион(область)"
#define LG_VCARD_ADR_PCODE    "Почтовый код"
#define LG_VCARD_ADR_CTRY     "Страна"
#define LG_VCARD_URL        "Домашняя страница"
#define LG_VCARD_DESC       "О себе"
#define LG_VCARD_TZ         "Временной пояс"
#define LG_VCARD_AVATAR     "Аватара"
//jid_enter_ui
#define LG_JEDELCONTACT     "Удалить контакт:"
#define LG_JEASK            "Запросить подписку:"
#define LG_JEGROUP          "Группа:"
#define LG_JENOJID          "Нет JIDа!"
#endif //RU

///////////////////////////////////////////////////////////////////////////////////////////
//
//    Ukrainian : Недоработан!
//
///////////////////////////////////////////////////////////////////////////////////////////
#ifdef LANG_UA
#define LG_SELECT           "Вибір"
#define LG_BACK             "Назад"
#define LG_OK               "Добре"
#define LG_CLOSE            "Закрити"
#define LG_MENU             "Меню"
#define LG_CANCEL           "Відмінити"
#define LG_EXIT             "Вихід"
#define LG_HELP             "Допомога"
#define LG_UPDATE           "Оновити"
//status_schange.c
#define LG_STATUSSEL        "Вибір статусу"
#define LG_STONLINE         "В мережі"
#define LG_STCHAT           "Готовий до розмови"
#define LG_STAWAY           "Відсутній"
#define LG_STXA             "Недоступний"
#define LG_STDND            "Зайнятий"
#define LG_STINVIS          "Невидимий"
#define LG_STOFFLINE        "Оффлайн"
#define LG_STATUS           "Статус"
#define LG_ENTERTEXTSTATUS  "Введіть текст статусу:"
#define LG_PRIORITY         "Приоритет:"
//MUC_Enter_UI.c
#define LG_NONAMECONF       "Им'я конференції не заповнено!"
#define LG_ENTERMUC         "Вхід в MUC"
#define LG_NAMEMUC          "Им'я конференції:"
#define LG_NICK             "Нік:"
#define LG_GETMESSAGECOUNT  "Отримати повідомлень:"
//message_list.c
#define LG_NOSENDNULLMESS   "Не можна відіслати порожнє повідомлення!"
#define LG_NEW              "Нове..."
//message_cmds.c
#define LG_SELCOMMAND       "Вибір команди..."
#define LG_SELTEMPLATE      "Вибір шаблону..."
#define LG_SELSMILE         "Вибір смайлу..."
#define LG_SELECT2          "Вибір..."
#define LG_CONTRESOURCES    "Ресурси..."
#define LG_CONTRESOURCE     "Ніки"
#define LG_COMMANDS         "Команди"
#define LG_MSGTEMPLATE      "Шаблони повідомлень"
#define LG_SMILE            "Смайли"
#define LG_CLOSEDLG         "Закрити діалог"
//mainmenu.c
#define LG_CONTACT          "Контакт"
#define LG_STATUS           "Статус"
#define LG_MUC              "Конференція"
#define LG_BOOKMARK         "Закладки"
#define LG_MVIBRA           "Режим вібри"
#define LG_MSOUND           "Режим звуку"
#define LG_MOFFLINE         "Офф. контакти"
#define LG_SETTINGS         "Налаштування"
#define LG_ABOUT            "Про эльф..."
#define LG_COLOR            "Кольори"
#define LG_ADDCONTACT       "Додати контакт"
#define LG_PLAYERSTATUS     "PlayerStatus"
//main.c
#define LG_EXITSIEJC        "Покинути SieJC?"
#define LG_ZLIBNOSASL       "ZLib не працює без SASL!"
#define LG_ENTERLOGPAS      "Введіть логін/пароль!"
#define LG_PLATFORMM        "Платформа не відповідає!"
#define LG_ASTARTED         "Вже виконується!"
//jabber_util.c
#define LG_MUCEXITDONE      "Вихід из MUC виконано!"
#define LG_VERINFO          "Version Info:\nName:%s\nVersion:%s\nOS:%s"
#define LG_TIMEINFO         "Time Info:\nUTC:%s\nTime Zone:%s\n:>%s"
#define LG_LASTACTIVMSG     "IDLE: %d d. %d hr. %d min. %d sec." //почемуто кирилица вызывает Bad UTF encoding..
//item_info.c
#define LG_ITEMIHDR         "Контакт інфо"
#define LG_ELROSTER         "Елемент ростеру"
#define LG_OFFLORCONTTR     "Оффлайн або контакт із транспорту"
#define LG_MUCPART          "Учасник конференції"
#define LG_JTRANSP          "Данний контакт є транспортом Jabber"
#define LG_GROUPROSTER      "Група ростеру"
#define LG_RESOURCE         "Ресурс:"
#define LG_PRIORITY         "Приоритет:"
#define LG_REALJID          "Реальний JID:"
#define LG_STATUS2          "Статус:"
#define LG_PRIVILEGES       "Привілеї:"
#define LG_ROLE             "Роль:"
#define LG_POSIBLCLIENT     "Можливості клієнта:"
#define LG_MUCSABJECT       "Тема:"
//#define LG_MUCNICK          "Нік:"
#define LG_ISUBSCRIBE       "Авторизація:"
//history.c
#define LG_ERRORWH          "Помилка I/O #%u при запису історії!"
//cont_menu.c
#define LG_MENUCONTACT      "Меню контакту"
#define LG_UNKACTION        "Дія невідома або не підтримується!"
#define LG_ABANDON          "Покинути"
#define LG_MUC_ADMIN        "muc#admin"
#define LG_KIK              "Кік"
#define LG_BAN              "Бан"
#define LG_LVOISE           "Відняти голос"     
#define LG_GVOISE           "Дати голос"
#define LG_PARTICIPANT      "Відняти членство"
#define LG_MEMBER           "Дати членство"
#define LG_MODERATOR        "Дати модератора"
#define LG_MODERATOR_REMOVE "Відняти модератора"
#define LG_ADMIN            "Дати адміна"
#define LG_OWNER            "Дати власника"
#define LG_VERCLIENT        "Версія клієнту"
#define LG_INFOFDISC        "Інфо із Disco"
#define LG_ON               "Включити"
#define LG_OFF              "Відключити"
#define LG_NOSUPACTION      "Немає підтримуваних дій"
#define LG_OHISTORY         "Історія"
#define LG_QUERYTIME        "Час"
#define LG_QUERYVCARD       "vCard"
#define LG_QUERYLAST        "Last Activity"
#define LG_SUBSCR           "Авторизація"
#define LG_EDIT             "Змінити"
#define LG_MUCCLEAR         "Очистити повідомлення"
#define LG_SUBSCRIBE        "Запросити"
#define LG_SUBSCRIBED       "Дозволити"
#define LG_UNSUBSCRIBED     "Відхилити"
#define LG_UNSUBSCRIBE      "Видалити"
#define LG_REASON           "Причина"
//clist_util.c
#define LG_AUTHORREM        "В авторизації відмовлено!"
#define LG_AUTHORGRANTED    "Авторизація надана!"
#define LG_MUCCROK          "Конференція створена успішно"
//bookmarks.c
#define LG_MENUBOOKMARK     "Меню закладок"
//config_data.c
#define LG_NO               "Ні"
#define LG_YES              "Так"
#define LG_DISABLED         "Відключити"
#define LG_ENABLED          "Включити"

#define LG_SETUPCONECT      "Налаштування підключення"
#define LG_LOGIN            "Логін"
#define LG_PASSWORD         "Пароль"
#define LG_SERVER           "Сервер"
#define LG_HOST             "Хост"
#define LG_HOSTTYPE         "Тип хосту"
#define LG_HOSTNAME         "Им'я"
#define LG_IPADRESS         "IP адреса"
#define LG_PORT             "Порт"
#define LG_AUTHTYPE         "Авторизація"
#define LG_ZLIBUSE          "Використання ZLib"
#define LG_RES              "Ресурс"
#define LG_HISTORY          "Історія"
#define LG_MUCHIST          "MUC історія"
#define LG_MUCDEF           "MUC за умовчанням"
#define LG_MUCDEFMSGCOUNT   "Кіл. отриманих повідомлень"
#define LG_MUCDEFNIK        "Нік за умовчанням"
#define LG_IDLEICON         "Розташування значка"
#define LG_POPUPDIS         "Відображати POPUP"
#define LG_COMPOSEV         "Події повідомлень"
#define LG_DELIVREP         "Delivery Report if required"

#define LG_SETUPSND         "Налаштування звуку"
#define LG_SNDVOL           "Гучність"
#define LG_SNDMSGSND        "Звук відправки"
#define LG_SNDMSGMUC        "Звук прийому із MUC"
#define LG_SNDMSGPM         "Звук прийому із PM"
#define LG_SNDONLINE        "Звук статуса онлайн"
#define LG_SNDOFFLINE       "Звук статуса оффлайн"
#define LG_SNDCOMPOSING     "Звук composing-повідомлень"

#define LG_SETUPPATH        "Налаштування шляхів"
#define LG_PATHHIST         "Історія"
#define LG_PATHPIC          "Картинки"
#define LG_PATHAVATARS      "Аватары"
#define LG_PATHCMD          "Команди"
#define LG_PATHMESG         "Повідомлення"
#define LG_PATHKNOWF        "Відомі особливості"
#define LG_PATHSMILECFG     "Конфіг смайлів"
#define LG_PATHSMILEDIR     "Каталог смайлів"
#define LG_DEFAULTDISK      "Диск за умовчанням"

#define LG_TEXTSTATUS       "Текст статусів"
#define LG_DEFSTATES        "Стани за умовчанням"

#define LG_VIEW             "Вигляд"
#define LG_ROSTER_FONT      "Шрифт ростеру"
#define LG_CHATS_FONT       "Шрифт списку повідомлень"
#define LG_SMALL_NORMAL_FONT "Малий"
#define LG_SMALL_BOLD_FONT  "Малий жирний"
#define LG_MID_NORMAL_FONT  "Середній"
#define LG_MID_BOLD_FONT    "Середній жирний"
#define LG_LARGE_NORMAL_FONT "Великий"
#define LG_LARGE_BOLD_FONT  "Великий жирний"
#define LG_UNDERLINING      "Підкреслення повідомлень"

#define LG_KBD_LAYOUT       "\"Разкладка\" клавіатури"
#define LG_KBD1             "Разкладка 1"
#define LG_KBD2             "Разкладка 2"
#define LG_SKROLL           "Скролінг"

#define LG_AUTOSTATUS       "Автостатус"
#define LG_AS_ENABLED       "Включений"
#define LG_AS_TIME          "Час (в хвилинах)"
//vCard.c

#define LG_SHOW_AVATAR      "Показать аватару"

#define LG_VCARD_JABBERID   "JID"
#define LG_VCARD_FN         "Повне ім'я"
#define LG_VCARD_NICKNAME   "Нік"
#define LG_VCARD_N_FAMILY   "Фамілія"
#define LG_VCARD_N_GIVEN    "Им'я"
#define LG_VCARD_N_MIDDLE   "По батькові"
#define LG_VCARD_N_PREFIX   "LG_VCARD_N_PREFIX"
#define LG_VCARD_N_SUFFIX   "LG_VCARD_N_SUFFIX"

#define LG_VCARD_BDAY       "День народження"
#define LG_VCARD_GENDER     "Стать"
#define LG_VCARD_ORGNAME    "Назва організації"
#define LG_VCARD_ORGUNIT    "Відділ організації"
#define LG_VCARD_TITLE      "Назва посади"
#define LG_VCARD_ROLE       "Посада"
#define LG_VCARD_EMAIL      "E-Mail"

#define LG_VCARD_EMAIL_HOME          "EMAIL_HOME"
#define LG_VCARD_EMAIL_WORK          "EMAIL_WORK"
#define LG_VCARD_EMAIL_INTERNET      "EMAIL_INTERNET"
#define LG_VCARD_EMAIL_PREF          "EMAIL_PREF"
#define LG_VCARD_EMAIL_X400          "EMAIL_X400"

#define LG_VCARD_TEL_HOME   "LG_VCARD_TEL_HOME"
#define LG_VCARD_TEL_WORK   "LG_VCARD_TEL_WORK"
#define LG_VCARD_TEL_VOICE  "LG_VCARD_TEL_VOICE"
#define LG_VCARD_TEL_FAX    "LG_VCARD_TEL_FAX"
#define LG_VCARD_TEL_PAGER  "LG_VCARD_TEL_PAGER"
#define LG_VCARD_TEL_MSG    "LG_VCARD_TEL_MSG"
#define LG_VCARD_TEL_CELL   "LG_VCARD_TEL_CELL"
#define LG_VCARD_TEL_VIDEO  "LG_VCARD_TEL_VIDEO"
#define LG_VCARD_TEL_BBS    "LG_VCARD_TEL_BBS"
#define LG_VCARD_TEL_MODEM  "LG_VCARD_TEL_MODEM"
#define LG_VCARD_TEL_ISDN   "LG_VCARD_TEL_ISDN"
#define LG_VCARD_TEL_PCS    "LG_VCARD_TEL_PCS"
#define LG_VCARD_TEL_PREF   "LG_VCARD_TEL_PREF"
#define LG_VCARD_TEL_NUMBER "LG_VCARD_TEL_NUMBER"

#define LG_VCARD_ADR_HOME   "ADR_HOME"
#define LG_VCARD_ADR_WORK   "ADR_WORK"
#define LG_VCARD_ADR_POSTAL "ADR_POSTAL"
#define LG_VCARD_ADR_PARCEL "ADR_PARCEL"
#define LG_VCARD_ADR_DOM    "ADR_DOM"
#define LG_VCARD_ADR_PREF   "ADR_PREF"
#define LG_VCARD_ADR_POBOX  "ADR_POBOX"
#define LG_VCARD_ADR_EXTADD "ADR_EXTADD"
#define LG_VCARD_ADR_STREET "ADR_STREET"
#define LG_VCARD_ADR_LOCALITY "ADR_LOCALITY"
#define LG_VCARD_ADR_REGION          "Область"
#define LG_VCARD_ADR_PCODE           "Поштовий код"
#define LG_VCARD_ADR_CTRY            "Держава"

#define LG_VCARD_URL        "Домашня сторінка"
#define LG_VCARD_DESC       "Про себе"
#define LG_VCARD_TZ         "Часовий пояс"
#define LG_VCARD_AVATAR     "Аватара"
//jid_enter_ui
#define LG_JEDELCONTACT     "Видалити контакт:"
#define LG_JEASK            "Запросити підпис:"
#define LG_JEGROUP          "Група:"
#define LG_JENOJID          "JID відсутній!"
#endif //UA

///////////////////////////////////////////////////////////////////////////////////////////
//
//    English : Недоработан!
//
///////////////////////////////////////////////////////////////////////////////////////////
#ifdef LANG_EN
#define LG_SELECT           "Select"
#define LG_BACK             "Back"
#define LG_OK               "OK"
#define LG_CLOSE            "Close"
#define LG_MENU             "Menu"
#define LG_CANCEL           "Cancel"
#define LG_EXIT             "Exit"
#define LG_HELP             "Help"
#define LG_UPDATE           "Update"
//status_schange.c
#define LG_STATUSSEL        "Status choice"
#define LG_STONLINE         "online"
#define LG_STCHAT           "chat"
#define LG_STAWAY           "away"
#define LG_STXA             "xa"
#define LG_STDND            "dnd"
#define LG_STINVIS          "invisible"
#define LG_STOFFLINE        "offline"
#define LG_STATUS           "Status"
#define LG_ENTERTEXTSTATUS  "Enter status text:"
#define LG_PRIORITY         "Priority:"
//MUC_Enter_UI.c
#define LG_NONAMECONF       "A conference name is empty!"
#define LG_ENTERMUC         "Join MUC"
#define LG_NAMEMUC          "MUC name:"
#define LG_NICK             "Nickname:"
#define LG_GETMESSAGECOUNT  "Number of messages:"
//message_list.c
#define LG_NOSENDNULLMESS   "It is impossible to send an empty message!"
#define LG_NEW              "New..."
//message_cmds.c
#define LG_SELCOMMAND       "Select command..."
#define LG_SELTEMPLATE      "Select template..."
#define LG_SELSMILE         "Select smile..."
#define LG_SELECT2          "Select..."
#define LG_CONTRESOURCES    "Resource..."  //както подругому надо
#define LG_CONTRESOURCE     "Nicknames"
#define LG_COMMANDS         "Commands"
#define LG_MSGTEMPLATE      "Templates"
#define LG_SMILE            "Smiles"
#define LG_CLOSEDLG         "Close"
//mainmenu.c
#define LG_CONTACT          "Contact"
#define LG_STATUS           "Status"
#define LG_MUC              "MUC"
#define LG_BOOKMARK         "Bookmarks"
#define LG_MVIBRA           "Vibra mode"
#define LG_MSOUND           "Sound mode"
#define LG_MOFFLINE         "Show Offline"
#define LG_SETTINGS         "Settings"
#define LG_ABOUT            "About..."
#define LG_COLOR            "Colors"
#define LG_ADDCONTACT       "Add contact"
#define LG_PLAYERSTATUS     "PlayerStatus"
//main.c
#define LG_EXITSIEJC        "Exit SieJC?"
#define LG_ZLIBNOSASL       "ZLib doesn't work without SASL!"
#define LG_ENTERLOGPAS      "Enter login/password!"
#define LG_PLATFORMM        "Target platform mismatch!"
#define LG_ASTARTED         "Already started"
//jabber_util.c
#define LG_MUCEXITDONE      "Leave MUC ok"
#define LG_VERINFO          "Version Info:\nName:%s\nVersion:%s\nOS:%s"
#define LG_TIMEINFO         "Time Info:\nUTC:%s\nTime Zone:%s\n:>%s"
#define LG_LASTACTIVMSG     "IDLE: %d d. %d hr. %d min. %d sec."
//item_info.c
#define LG_ITEMIHDR         "Contact Info"
#define LG_ELROSTER         "Roster elements"
#define LG_OFFLORCONTTR     "Offline or transport contact"
#define LG_MUCPART          "MUC partcipiant"
#define LG_JTRANSP          "This contact is a transport"
#define LG_GROUPROSTER      "Roster group"
#define LG_RESOURCE         "Resource:"
#define LG_PRIORITY         "Priority:"
#define LG_REALJID          "Real JID:"
#define LG_STATUS2          "Status:"
#define LG_PRIVILEGES       "Affiliation:"
#define LG_ROLE             "Role:"
#define LG_POSIBLCLIENT     "Client features:"
#define LG_MUCSABJECT       "Sabject:"
//#define LG_MUCNICK          "Nick:"
#define LG_ISUBSCRIBE       "Subscibe:"
//history.c
#define LG_ERRORWH          "I/O Error #%u while trying to write the history"
//cont_menu.c
#define LG_MENUCONTACT      "Contact menu"
#define LG_UNKACTION        "Unknown or unsupported action!"
#define LG_ABANDON          "Leave MUC"
#define LG_MUC_ADMIN        "muc#admin"
#define LG_KIK              "Kick"
#define LG_BAN              "Ban"
#define LG_LVOISE           "Revoke voice"
#define LG_GVOISE           "Grant voice"
#define LG_PARTICIPANT      "Unaffiliate"
#define LG_MEMBER           "Grant Membership"
#define LG_MODERATOR        "Grant Moderator"
#define LG_MODERATOR_REMOVE "Remove Moderator"
#define LG_ADMIN            "Grant Admin"
#define LG_OWNER            "Grant Ownership"
#define LG_VERCLIENT        "Version"
#define LG_INFOFDISC        "Disco info"
#define LG_ON               "Connect"
#define LG_OFF              "Disconnect"
#define LG_NOSUPACTION      "No supported action"
#define LG_OHISTORY         "History"
#define LG_QUERYTIME        "Time"
#define LG_QUERYVCARD       "vCard"
#define LG_QUERYLAST        "Last Activity"
#define LG_SUBSCR           "Subscription"
#define LG_EDIT             "Edit"
#define LG_MUCCLEAR         "Clear messages"
#define LG_SUBSCRIBE        "Ask"
#define LG_SUBSCRIBED       "Allow subscription"
#define LG_UNSUBSCRIBED     "Deny subscription"
#define LG_UNSUBSCRIBE      "Remove"
#define LG_REASON           "Reason"
//clist_util.c
#define LG_AUTHORREM        "Authorization was removed!"
#define LG_AUTHORGRANTED    "Authorization was granted!"
#define LG_MUCCROK          "MUC created OK!"
//bookmarks.c
#define LG_MENUBOOKMARK     "Bookmarks menu"
//config_data.c
#define LG_NO               "No"
#define LG_YES              "Yes"
#define LG_DISABLED         "Disabled"
#define LG_ENABLED          "Enabled"
#define LG_SETUPCONECT      "Connection setup"
#define LG_LOGIN            "Login"
#define LG_PASSWORD         "Password"
#define LG_SERVER           "Server"
#define LG_HOST             "Host"
#define LG_HOSTTYPE         "Host type"
#define LG_HOSTNAME         "Host name"
#define LG_IPADRESS         "IP address"
#define LG_PORT             "Port"
#define LG_AUTHTYPE         "Auth type"
#define LG_ZLIBUSE          "ZLib usage"
#define LG_RES              "Resource"
#define LG_HISTORY          "History"
#define LG_MUCHIST          "MUC history"
#define LG_MUCDEF           "Default MUC"
#define LG_MUCDEFMSGCOUNT   "MUC message count"
#define LG_MUCDEFNIK        "Default MUC nick"
#define LG_IDLEICON         "Idle icon position"
#define LG_POPUPDIS         "Display pop-ups"
#define LG_COMPOSEV         "Composing Events"
#define LG_DELIVREP         "Delivery Report if required"

#define LG_SETUPSND         "Sounds setup"
#define LG_SNDVOL           "sndVolume"
#define LG_SNDMSGSND        "Sound Msg Send"
#define LG_SNDMSGMUC        "Sound Msg Conf"
#define LG_SNDMSGPM         "Sound Msg PM"
#define LG_SNDONLINE        "Sound for online-status"
#define LG_SNDOFFLINE       "Sound for offline-status"
#define LG_SNDCOMPOSING     "Sound for composing-events"

#define LG_SETUPPATH        "Paths setup"
#define LG_PATHHIST         "History path"
#define LG_PATHPIC          "Pictures path"
#define LG_PATHAVATARS      "Avatars path"
#define LG_PATHCMD          "Commands path"
#define LG_PATHMESG         "Messages path"
#define LG_PATHKNOWF        "Known features"
#define LG_PATHSMILECFG     "Smiles config"
#define LG_PATHSMILEDIR     "Smiles .png path"
#define LG_DEFAULTDISK      "Default disc"

#define LG_TEXTSTATUS       "Statuses text"
#define LG_DEFSTATES        "Default states"

#define LG_VIEW             "View"
#define LG_ROSTER_FONT      "Roster font"
#define LG_CHATS_FONT       "Messagelist font"
#define LG_SMALL_NORMAL_FONT "Small"
#define LG_SMALL_BOLD_FONT  "Small bold"
#define LG_MID_NORMAL_FONT  "Medium"
#define LG_MID_BOLD_FONT    "Medium bold"
#define LG_LARGE_NORMAL_FONT "Large"
#define LG_LARGE_BOLD_FONT  "Large bold"
#define LG_UNDERLINING      "Underline messages"

#define LG_KBD_LAYOUT       "Keyboard \"layout\""
#define LG_KBD1             "Layout 1"
#define LG_KBD2             "Layout 2"
#define LG_SKROLL           "SCROLL"

#define LG_AUTOSTATUS       "Autostatus"
#define LG_AS_ENABLED       "Enable"
#define LG_AS_TIME          "Time (minutes)"
//vCard.c

#define LG_SHOW_AVATAR      "Show avatar"

#define LG_VCARD_JABBERID   "JID"
#define LG_VCARD_FN         "Full name"
#define LG_VCARD_NICKNAME   "Nickname"
#define LG_VCARD_N_FAMILY   "LG_VCARD_N_FAMILY"
#define LG_VCARD_N_GIVEN    "LG_VCARD_N_GIVEN"
#define LG_VCARD_N_MIDDLE   "LG_VCARD_N_MIDDLE"
#define LG_VCARD_N_PREFIX   "LG_VCARD_N_PREFIX"
#define LG_VCARD_N_SUFFIX   "LG_VCARD_N_SUFFIX"
#define LG_VCARD_BDAY       "Birthday"
#define LG_VCARD_GENDER     "Gender"
#define LG_VCARD_ORGNAME    "Org. name"
#define LG_VCARD_ORGUNIT    "Org. unit"
#define LG_VCARD_TITLE      "Title"
#define LG_VCARD_ROLE       "Role"
#define LG_VCARD_EMAIL      "E-Mail"
#define LG_VCARD_EMAIL_HOME          "EMAIL_HOME"
#define LG_VCARD_EMAIL_WORK          "EMAIL_WORK"
#define LG_VCARD_EMAIL_INTERNET      "EMAIL_INTERNET"
#define LG_VCARD_EMAIL_PREF          "EMAIL_PREF"
#define LG_VCARD_EMAIL_X400          "EMAIL_X400"

#define LG_VCARD_TEL_HOME   "LG_VCARD_TEL_HOME"
#define LG_VCARD_TEL_WORK   "LG_VCARD_TEL_WORK"
#define LG_VCARD_TEL_VOICE  "LG_VCARD_TEL_VOICE"
#define LG_VCARD_TEL_FAX    "LG_VCARD_TEL_FAX"
#define LG_VCARD_TEL_PAGER  "LG_VCARD_TEL_PAGER"
#define LG_VCARD_TEL_MSG    "LG_VCARD_TEL_MSG"
#define LG_VCARD_TEL_CELL   "LG_VCARD_TEL_CELL"
#define LG_VCARD_TEL_VIDEO  "LG_VCARD_TEL_VIDEO"
#define LG_VCARD_TEL_BBS    "LG_VCARD_TEL_BBS"
#define LG_VCARD_TEL_MODEM  "LG_VCARD_TEL_MODEM"
#define LG_VCARD_TEL_ISDN   "LG_VCARD_TEL_ISDN"
#define LG_VCARD_TEL_PCS    "LG_VCARD_TEL_PCS"
#define LG_VCARD_TEL_PREF   "LG_VCARD_TEL_PREF"
#define LG_VCARD_TEL_NUMBER "LG_VCARD_TEL_NUMBER"

#define LG_VCARD_ADR_HOME   "ADR_HOME"
#define LG_VCARD_ADR_WORK   "ADR_WORK"
#define LG_VCARD_ADR_POSTAL "ADR_POSTAL"
#define LG_VCARD_ADR_PARCEL "ADR_PARCEL"
#define LG_VCARD_ADR_DOM    "ADR_DOM"
#define LG_VCARD_ADR_PREF   "ADR_PREF"
#define LG_VCARD_ADR_POBOX  "ADR_POBOX"
#define LG_VCARD_ADR_EXTADD "ADR_EXTADD"
#define LG_VCARD_ADR_STREET "ADR_STREET"
#define LG_VCARD_ADR_LOCALITY   "ADR_LOCALITY"
#define LG_VCARD_ADR_ADR_REGION "ADR_REGION"
#define LG_VCARD_ADR_ADR_PCODE  "ADR_PCODE"
#define LG_VCARD_ADR_ADR_CTRY   "ADR_CTRY"

#define LG_VCARD_URL        "Homepage"
#define LG_VCARD_DESC       "Description"
#define LG_VCARD_TZ         "Time zone"
#define LG_VCARD_AVATAR     "Avatar"
//jid_enter_ui
#define LG_JEDELCONTACT     "Delete contact:"
#define LG_JEASK            "Ask subscribe:"
#define LG_JEGROUP          "Group:"
#define LG_JENOJID          "No JID!"
#endif //EN


#endif
