#ifndef _LANG_H_
#define _LANG_H_

#define COPYRIGHT               "ProPlayer v0.1\n(c) VedaN,\nKIBER-DEMON,\nEraser,\nEvilFox"
#define ELF_NAME                "ProPlayer"
//------------------------------------------------------------------------------
#ifdef LANG_RU
#define LGP_SELECT              "Выбор"
#define LGP_BACK                "Отмена"
#define LGP_EDIT                "Редактир."
#define LGP_OK                  "OK"
//Меню
#define LGP_OPEN                "Открыть..."
#define LGP_OPENFILLE           "Открыть файл"
#define LGP_OPENPLAYLIST        "Открыть плэйлист"
#define LGP_PLAYMODE            "Режим воспр."
#define LGP_POSITIONING         "Позиционирование"
#define LGP_EQUALISER           "Эквалайзер"
#define LGP_EDITTAG             "Редактор тэгов"
#define LGP_OPTIONS             "Настройки"
#define LGP_SUBMENU             "Информация"
#define LGP_ABOUT               "Об эльфе..."
#define LGP_EXIT                "Выход"

#define LGP_PLAY                "Воспр."
#define LGP_PAUSE               "Пауза"
#define LGP_RESUME              "Возобнов."
#define LGP_VOLDOWN             "Громкость-"
#define LGP_VOLUP               "Громкость+"
#define LGP_PREV                "Предыдущий"
#define LGP_NEXT                "Следующий"

#define LGP_ATUOEXIT            "Авто выход"
#define LGP_START_AUTOEXIT      "Запустить"
#define LGP_STOP_AUTOEXIT       "Остановить"
#define LNG_TEXT_PLAYER         "ProPlayer"
#define LNG_MENU                "Меню"
#define LNG_STOP                "Стоп"
#define LNG_PLAYING             "Воспр."
#define LNG_PAUSE               "Пауза"
#define LNG_VOL                 "Громкость"
#define LNG_STATUS              "Статус"
#define LNG_PLAYMODE            "Режим"
#define LNG_MODE_T2B            "Все"
#define LNG_MODE_B2T            "Все наоборот"
#define LNG_MODE_SHUF           "Вразброс"
#define LNG_AUTO_SHUTDOWN       "Выключение"
#define LNG_AUTO_QUIT           "Выход"
#define LNG_SWITCHOFF_TIME      "Время: "
#define LNG_EXIT_TIME           "Время: "
#define LGP_ROOT                "Открыть:"
//Режим воспр.
#define LGP_CYCLETOP2BOTTOM     "Все"
#define LGP_CYCLEBOTTOM2TOP     "Все наоборот"
#define LGP_SHUFFLE             "Вразброс"
//Эквалайзер
#define LNG_EQUALISER           "Эквалайзер"
#define LNG_EQUALISER_CLASSICAL "Classical"
#define LNG_EQUALISER_CLUB      "Club"
#define LNG_EQUALISER_DANCE     "Dance"
#define LNG_EQUALISER_BASS      "Bass"
#define LNG_EQUALISER_MEGABASS  "MegaBass"
#define LNG_EQUALISER_TREBLE    "Treble"
#define LNG_EQUALISER_PARTY     "Party"
#define LNG_EQUALISER_POP       "Pop"
#define LNG_EQUALISER_REGGAE    "Reggae"
#define LNG_EQUALISER_ROCK      "Rock"
#define LNG_EQUALISER_SOFT      "Soft"
//Информация
#define LGP_HELP              "Помощь"
#define LGP_RESPECTS          "Респект allsiemens.com и svn://cbsie.dyndns.info"
#endif
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
#ifdef LANG_EN
//Английский
#define LGP_SELECT              "Select"
#define LGP_BACK                "Back"
#define LGP_EDIT                "Edit"
#define LGP_OK                  "OK"
//Меню
#define LGP_OPEN                "Open..."
#define LGP_OPENFILLE           "OpenFille"
#define LGP_OPENPLAYLIST        "OpenPlaylist"
#define LGP_PLAYMODE            "PlayMode"
#define LGP_POSITIONING         "Positioning"
#define LGP_EQUALISER           "Equaliser"
#define LGP_EDITTAG             "EditTag"
#define LGP_OPTIONS             "Options"
#define LGP_SUBMENU             "Info"
#define LGP_ABOUT               "About"
#define LGP_EXIT                "Exit"

#define LGP_PLAY                "Play"
#define LGP_PAUSE               "Pause"
#define LGP_RESUME              "Resume"
#define LGP_VOLDOWN             "VolDown"
#define LGP_VOLUP               "VolUP"
#define LGP_PREV                "Previous"
#define LGP_NEXT                "Next"


#define LGP_ATUOEXIT            "AutoExit"
#define LGP_START_AUTOEXIT      "StartAutoExit"
#define LGP_STOP_AUTOEXIT       "StopAutoExit"
#define LNG_TEXT_PLAYER         "MediaPlayer"
#define LNG_MENU                "Menu"
#define LNG_STOP                "Stop"
#define LNG_PLAYING             "Play"
#define LNG_PAUSE               "Pause"
#define LNG_VOL                 "Volume"
#define LNG_STATUS              "Status"
#define LNG_PLAYMODE            "Mode"
#define LNG_MODE_T2B            "All"
#define LNG_MODE_B2T            "ContraryAll"
#define LNG_MODE_SHUF           "Shufle"
#define LNG_AUTO_SHUTDOWN       "Shutdown"
#define LNG_AUTO_QUIT           "Quit"
#define LNG_SWITCHOFF_TIME      "SwitchOff: "
#define LNG_EXIT_TIME           "Exit: "
#define LGP_ROOT                "Root:"
//Режим воспр.
#define LGP_CYCLETOP2BOTTOM     "CycleTop2Bottom"
#define LGP_CYCLEBOTTOM2TOP     "CycleBottom2Top"
#define LGP_SHUFFLE             "Shuffle"
//Эквалайзер
#define LNG_EQUALISER           "Equaliser"
#define LNG_EQUALISER_CLASSICAL "Classical"
#define LNG_EQUALISER_CLUB      "Club"
#define LNG_EQUALISER_DANCE     "Dance"
#define LNG_EQUALISER_BASS      "Bass"
#define LNG_EQUALISER_MEGABASS  "MegaBass"
#define LNG_EQUALISER_TREBLE    "Treble"
#define LNG_EQUALISER_PARTY     "Party"
#define LNG_EQUALISER_POP       "Pop"
#define LNG_EQUALISER_REGGAE    "Reggae"
#define LNG_EQUALISER_ROCK      "Rock"
#define LNG_EQUALISER_SOFT      "Soft"
//Информация
#define LGP_HELP              "Help"
#define LGP_RESPECTS          "Respect allsiemens.com and svn://cbsie.dyndns.info"
#endif
#endif
//------------------------------------------------------------------------------
