
void lgpInitLangPack ();
void lgpFreeLangPack ();

enum LGP_ID
{
  LGP_CantOpenFile=0,
  LGP_CantLoadAuthCode,
  LGP_HistoryFileFailed,
  LGP_CfgUpdated,
  LGP_RefUnderConstruction,
  LGP_RefEmpty,
  LGP_Error,
  LGP_Stop,
  LGP_WaitDNR,
  LGP_IpConnect,
  LGP_GetHostByName,
  LGP_FaultDNR,
  LGP_OkDNR,
  LGP_OpenSocket,
  LGP_ConnectFault,
  LGP_AnswerDNR,
  LGP_Connected,
  LGP_DataReceived,
  LGP_RemoteClosed,
  LGP_LocalClosed,
  LGP_InetBussy,
  LGP_EnableGPRS,
  LGP_UnderConstruction,
  LGP_Select,
  LGP_Close,
  LGP_Ok,
  LGP_Cancel,
  LGP_Templates,
  LGP_NameHeader,
  LGP_LinkHeader,
  LGP_TextHeader,
  LGP_SearchEngine,
  LGP_SelectHeader,
  LGP_EnterHeader,
  LGP_Add,
  LGP_BookmarkHeader,
  LGP_Save,
  LGP_NewBookmark,
  LGP_Absent,
  LGP_OptionsHeader,
  LGP_Edit,
  LGP_Delete,
  LGP_Back,
  LGP_Options,
  LGP_SelectBookmarkHeader,
  LGP_SearchHeader,
  LGP_Go,
  LGP_HistoryHeader,
  LGP_AddressHeader,
  LGP_Menu,
  LGP_GoTo,
  LGP_Bookmarks,
  LGP_History,
  LGP_Settings,
  LGP_Exit,
  LGP_Search,
  LGP_LangCode,
  LGP_Reserve2,
  LGP_Reserve3,
  LGP_Reserve4,
  LGP_Reserve5,
  LGP_Reserve6,
  LGP_Reserve7,
  LGP_DATA_NUM
};

extern char *lgpData[LGP_DATA_NUM];
